include:
  - template: Auto-DevOps.gitlab-ci.yml
# build-dotnet:
#   image: mcr.microsoft.com/dotnet/sdk:8.0
#   stage: build
#   before_script:
#     - dotnet restore
#   script:
#     - dotnet build -o /app
#     - dotnet publish -o /publish
#   artifacts:
#     paths:
#       - /publish
#       - /app
# deploy-dotnet:
#   image: mcr.microsoft.com/dotnet/aspnet:8.0
#   stage: deploy
#   script:
#     - echo "Deploying to production"
#     - dotnet UrgentHub.dll
