<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <PropertyGroup>
    <EfCoreVersion>10.0.9</EfCoreVersion>
    <MicrosoftExtVersion>10.0.9</MicrosoftExtVersion>
  </PropertyGroup>
  <!-- Application Dependencies -->
  <ItemGroup Label="App">
    <PackageVersion Include="Amazon.AspNetCore.DataProtection.SSM" Version="4.0.3" />
    <PackageVersion Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageVersion Include="AWSSDK.Core" Version="4.0.9.1" />
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.4.6" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.24.3" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="$(MicrosoftExtVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="$(MicrosoftExtVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="$(MicrosoftExtVersion)" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="$(MicrosoftExtVersion)" />
  </ItemGroup>
  <!-- Test Dependencies -->
  <ItemGroup Label="Test">
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="coverlet.msbuild" Version="10.0.1" />
  </ItemGroup>
</Project>
