// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

public partial class IntMgrPartnerDirectoryLinkRequest
{
    public int Id { get; set; }

    public int RequestingTenantId { get; set; }

    public int TargetTenantId { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public string DeclineReason { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Tenant RequestingTenant { get; set; }

    public virtual Tenant TargetTenant { get; set; }
}