// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

public partial class IntMgrPartnerDirectoryListing
{
    public int TenantId { get; set; }

    public string BaseUrl { get; set; }

    public string Description { get; set; }

    public string Region { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Tenant Tenant { get; set; }
}