// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UrgentHub.Models.Master;

public partial class MasterContext : DbContext
{
    public MasterContext(DbContextOptions<MasterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tenant> Tenants { get; set; }

    public virtual DbSet<TenantUser> TenantUsers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tenant>(entity =>
        {
            entity.ToTable("Tenant");

            entity.HasIndex(e => e.Dbconnection, "IX_Tenant_DBConnection");

            entity.HasIndex(e => e.Name, "IX_Tenant_Name").IsUnique();

            entity.Property(e => e.Code).HasMaxLength(500);
            entity.Property(e => e.Dbconnection)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("DBConnection");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<TenantUser>(entity =>
        {
            entity.ToTable("TenantUser");

            entity.HasIndex(e => new { e.TenantId, e.UserId }, "IX_TenantUser_TenantId_UserId").IsUnique();

            entity.HasIndex(e => e.UserId, "IX_TenantUser_UserId");

            entity.HasOne(d => d.Tenant).WithMany(p => p.TenantUsers)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TenantUser_Tenant");

            entity.HasOne(d => d.User).WithMany(p => p.TenantUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TenantUser_User");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "IX_User").IsUnique();

            entity.HasIndex(e => e.CurrentTenantId, "IX_User_CurrentTenantId");

            entity.HasIndex(e => e.Email, "IX_User_Email").IsUnique();

            entity.HasIndex(e => e.ResetKey, "IX_User_ResetKey");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ResetKey).HasMaxLength(50);
            entity.Property(e => e.Salt)
                .IsRequired()
                .HasMaxLength(64);

            entity.HasOne(d => d.CurrentTenant).WithMany(p => p.Users)
                .HasForeignKey(d => d.CurrentTenantId)
                .HasConstraintName("FK_User_Tenant");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}