// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

/// <summary>
/// Where a courier's own Integration Manager lives, and - by the existence of the row - whether
/// Shopify is switched on for them at all.
/// <para>
/// Keyed on the tenant, one row or none. A tenant with no row is not offered to a merchant signing
/// in: there is nowhere to hand their store to, and naming the courier anyway would tell the public
/// front door about a relationship it has no business knowing.
/// </para>
/// <para>
/// Written by the courier's own Integration Manager, which is the only thing that knows its own
/// public address. Read by Hub when resolving a merchant's couriers, and by the Shopify front door
/// when routing a request to one.
/// </para>
/// </summary>
public partial class ShopifyTenantHost
{
    /// <summary>The key. There is no surrogate: a tenant has one Integration Manager or none.</summary>
    public int TenantId { get; set; }

    public string IntegrationManagerUrl { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Tenant Tenant { get; set; }
}
