// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

public partial class ShopifyShopTenant
{
    /// <summary>
    /// A surrogate key. <see cref="Shop"/> is still the identity: UX_ShopifyShopTenant_Shop is what
    /// enforces one tenant per shop, which is the invariant this table exists for.
    /// </summary>
    public Guid Id { get; set; }

    public string Shop { get; set; }

    /// <summary>
    /// The store's display name, as a label only - never an identity, and nothing decides on it.
    /// <para>
    /// Written by the Shopify front door, which reads it from the Admin API at the one moment it
    /// holds an access token. Null when it has never been read, and it can go stale if a merchant
    /// renames their store without reconnecting. Hub does not write it.
    /// </para>
    /// </summary>
    public string ShopName { get; set; }

    public int TenantId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Tenant Tenant { get; set; }
}