// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

public partial class TenantUserSetting
{
    public int TenantUserSettingId { get; set; }

    public int TenantId { get; set; }

    public int UserId { get; set; }

    public string SettingName { get; set; }

    public string SettingValue { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual User User { get; set; }
}