// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrgentHub.Models.Master;

public partial class TenantUser
{
    public int TenantUserId { get; set; }

    public int TenantId { get; set; }

    public int UserId { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual User User { get; set; }
}