// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrgentHub.Models.Master;

public partial class Tenant
{
    public int TenantId { get; set; }

    public string Name { get; set; }

    public string Dbconnection { get; set; }

    public virtual ICollection<TenantUser> TenantUsers { get; set; } = new List<TenantUser>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}