// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models.Master;

public partial class TenantBranding
{
    public int TenantId { get; set; }

    public string CompanyName { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string PrimaryColour { get; set; }

    public string HeaderTextColour { get; set; }

    public string AccentColour { get; set; }

    public string FooterText { get; set; }

    public string DisclaimerText { get; set; }

    public string PaperSize { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }
}