// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UrgentHub.Models.Master;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public string ResetKey { get; set; }

    public int? CurrentTenantId { get; set; }

    public virtual Tenant CurrentTenant { get; set; }

    public virtual ICollection<TenantUser> TenantUsers { get; set; } = new List<TenantUser>();
}