// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class ClientType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ClientTypeFeature> ClientTypeFeatures { get; set; } = new List<ClientTypeFeature>();

    public virtual ICollection<TucClient> TucClients { get; set; } = new List<TucClient>();
}