// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class ClientTypeFeature
{
    public int ClientTypeFeatureId { get; set; }

    public int ClientTypeId { get; set; }

    public string FeatureKey { get; set; }

    public bool Visible { get; set; }

    public virtual ClientType ClientType { get; set; }

    public virtual Feature FeatureKeyNavigation { get; set; }
}