// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class ClientTypeFeature
{
    public int ClientTypeFeatureId { get; set; }

    public int ClientTypeId { get; set; }

    public string FeatureKey { get; set; }

    public bool Visible { get; set; }

    // DF Admin ceiling (Steve decision note 2026-09-01, step 3). Visible is
    // what the TENANT granted; this is whether they were allowed to. Effective
    // visibility is both - see FeatureResolver. Added by migration
    // 20260901143000_ClientTypeFeatureGrantableCeiling.sql, which MUST be
    // deployed before this code: EF selects the column on every read.
    public bool Grantable { get; set; } = true;

    public virtual ClientType ClientType { get; set; }

    public virtual Feature FeatureKeyNavigation { get; set; }
}