// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Hub.Models;

public partial class DespatchContext : DbContext
{
    public DespatchContext(DbContextOptions<DespatchContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblAfterhoursCourier> TblAfterhoursCouriers { get; set; }

    public virtual DbSet<TblFuelSurcharge> TblFuelSurcharges { get; set; }

    public virtual DbSet<TblSetting> TblSettings { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TucClient> TucClients { get; set; }

    public virtual DbSet<TucClientContact> TucClientContacts { get; set; }

    public virtual DbSet<TucCourier> TucCouriers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<TblAfterhoursCourier>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblAfter__3214EC27728AD932");

            entity.ToTable("tblAfterhoursCourier");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");

            entity.HasOne(d => d.Courier).WithMany(p => p.TblAfterhoursCouriers)
                .HasForeignKey(d => d.CourierId)
                .HasConstraintName("fk_tucCourier");
        });

        modelBuilder.Entity<TblFuelSurcharge>(entity =>
        {
            entity.HasKey(e => e.FuelSurchargeId);

            entity.ToTable("tblFuelSurcharge");

            entity.Property(e => e.FuelSurchargeId).HasColumnName("FuelSurchargeID");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.Start).HasColumnType("datetime");
            entity.Property(e => e.End).HasColumnType("datetime");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.PumpPrice).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.VehicleSizeId).HasColumnName("VehicleSizeID");
        });

        modelBuilder.Entity<TblSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId).IsClustered(false);

            entity.ToTable("tblSetting");

            entity.HasIndex(e => e.InvoiceTemplateId, "IX_InvoiceTemplateId");

            entity.HasIndex(e => e.PaymentTermId, "IX_PaymentTermId");

            entity.Property(e => e.SettingId).HasColumnName("SettingID");
            entity.Property(e => e.AccountsCodeBonus).HasMaxLength(50);
            entity.Property(e => e.AccountsCodePpd).HasMaxLength(50);
            entity.Property(e => e.AccountsDescriptionBonus).HasMaxLength(50);
            entity.Property(e => e.AccountsDescriptionPpd).HasMaxLength(50);
            entity.Property(e => e.AccountsItemCodeBonus).HasMaxLength(50);
            entity.Property(e => e.AccountsRefreshToken).HasMaxLength(200);
            entity.Property(e => e.AccountsStartDate).HasPrecision(3);
            entity.Property(e => e.AccountsTenantId).HasMaxLength(200);
            entity.Property(e => e.AddressValidationPass).HasMaxLength(50);
            entity.Property(e => e.AddressValidationUrl)
                .HasMaxLength(200)
                .HasColumnName("AddressValidationURL");
            entity.Property(e => e.AddressValidationUser).HasMaxLength(50);
            entity.Property(e => e.AdminEmail)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AllowPostingToOa).HasColumnName("AllowPostingToOA");
            entity.Property(e => e.ApplicationName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.BurstTheBubbleCourierId).HasColumnName("BurstTheBubbleCourierID");
            entity.Property(e => e.CommunicationFileDirectory)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CompanyAddress).HasMaxLength(100);
            entity.Property(e => e.CompanyBankNumber).HasMaxLength(100);
            entity.Property(e => e.ComposerExtrasPath).HasMaxLength(500);
            entity.Property(e => e.ContactUsEmailSubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CountryCode).HasMaxLength(50);
            entity.Property(e => e.CourierServiceProcessed).HasPrecision(3);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DataComClientId)
                .HasMaxLength(50)
                .HasColumnName("DataComClientID");
            entity.Property(e => e.DefaultClass).HasMaxLength(50);
            entity.Property(e => e.DefaultCourierWithholdingTaxPercentage).HasColumnType("decimal(8, 2)");
            entity.Property(e => e.DefaultDateRange)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DefaultItemCode).HasMaxLength(50);
            entity.Property(e => e.DefaultItemCodeFuel).HasMaxLength(50);
            entity.Property(e => e.DefaultRevenueAccount).HasMaxLength(50);
            entity.Property(e => e.DespatchUniqueEmailNotifyAddress).HasMaxLength(200);
            entity.Property(e => e.DpspayRoot)
                .HasMaxLength(200)
                .HasColumnName("DPSPayRoot");
            entity.Property(e => e.EnquiryEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FaxHeadLogo)
                .IsRequired()
                .HasColumnType("image");
            entity.Property(e => e.FaxHeadLogoSmall)
                .IsRequired()
                .HasColumnType("image");
            entity.Property(e => e.GoogleAnalyticsCode).HasMaxLength(50);
            entity.Property(e => e.GoogleMapApikey)
                .HasMaxLength(200)
                .HasColumnName("GoogleMapAPIKey");
            entity.Property(e => e.GoogleMapGeneratorRoot).HasMaxLength(200);
            entity.Property(e => e.GoogleMapRoot).HasMaxLength(50);
            entity.Property(e => e.GooglePlaceAutocompleteApikey)
                .HasMaxLength(200)
                .HasColumnName("GooglePlaceAutocompleteAPIKey");
            entity.Property(e => e.GoogleSmtpserver)
                .HasMaxLength(50)
                .HasColumnName("GoogleSMTPServer");
            entity.Property(e => e.GoogleSmtpserverActive).HasColumnName("GoogleSMTPServerActive");
            entity.Property(e => e.GoogleSmtpserverPass)
                .HasMaxLength(20)
                .HasColumnName("GoogleSMTPServerPass");
            entity.Property(e => e.GoogleSmtpserverUser)
                .HasMaxLength(50)
                .HasColumnName("GoogleSMTPServerUser");
            entity.Property(e => e.Gstrate)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("GSTRate");
            entity.Property(e => e.GstregistrationNumber)
                .HasMaxLength(100)
                .HasColumnName("GSTRegistrationNumber");
            entity.Property(e => e.InternetClientDetailsEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InternetClientDetailsSubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InternetInvoiceReportId).HasColumnName("InternetInvoiceReportID");
            entity.Property(e => e.InternetInvoiceSignatureReportId).HasColumnName("InternetInvoiceSignatureReportID");
            entity.Property(e => e.InternetJobEmailSubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InternetJobPoaemail)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("InternetJobPOAEmail");
            entity.Property(e => e.InternetJobPoaemailSubject)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("InternetJobPOAEmailSubject");
            entity.Property(e => e.InternetJobStaffId).HasColumnName("InternetJobStaffID");
            entity.Property(e => e.InternetRateScheduleReportId).HasColumnName("InternetRateScheduleReportID");
            entity.Property(e => e.InternetRoot)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InternetStatementReportId).HasColumnName("InternetStatementReportID");
            entity.Property(e => e.InvoiceMemo).HasMaxLength(100);
            entity.Property(e => e.JobDetailsReplyFromEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JobFeedbackSubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JobPackingReportId).HasColumnName("JobPackingReportID");
            entity.Property(e => e.JoinOurTeamEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JoinOurTeamReplyAttachment).HasMaxLength(500);
            entity.Property(e => e.JoinOurTeamReplyFromEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JoinOurTeamReplyMessage)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.JoinOurTeamReplySubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JoinOurTeamSubject)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.JournalCreatedBy).HasMaxLength(50);
            entity.Property(e => e.JournalEntityCode).HasMaxLength(10);
            entity.Property(e => e.JournalNarration).HasMaxLength(100);
            entity.Property(e => e.JournalTransactionCode).HasMaxLength(10);
            entity.Property(e => e.LastJobArchive).HasPrecision(3);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LetterHeadLogo)
                .IsRequired()
                .HasColumnType("image");
            entity.Property(e => e.MapRoot).HasMaxLength(200);
            entity.Property(e => e.NationwideAreaId).HasColumnName("NationwideAreaID");
            entity.Property(e => e.NewsImageDirectory)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Notes).HasColumnType("ntext");
            entity.Property(e => e.OpenforceActivationCode).HasMaxLength(100);
            entity.Property(e => e.OpenforceApiKey).HasMaxLength(50);
            entity.Property(e => e.OpenforceClientGuid).HasMaxLength(50);
            entity.Property(e => e.OpenforceClientId).HasMaxLength(100);
            entity.Property(e => e.ParentJobCourierId).HasColumnName("ParentJobCourierID");
            entity.Property(e => e.PpdAppliedDescription)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PpdCode).HasMaxLength(50);
            entity.Property(e => e.PpdDescription)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PpdItemCode).HasMaxLength(50);
            entity.Property(e => e.QuickBooksRefreshToken).HasMaxLength(200);
            entity.Property(e => e.RateGuideCommunicationTypeId).HasColumnName("RateGuideCommunicationTypeID");
            entity.Property(e => e.RatesGuideImagePath).HasMaxLength(500);
            entity.Property(e => e.ReceivableAccount).HasMaxLength(100);
            entity.Property(e => e.ReportDomain)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReportFolder).HasMaxLength(100);
            entity.Property(e => e.ReportPassword)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReportServicesUrl)
                .HasMaxLength(100)
                .HasColumnName("ReportServicesURL");
            entity.Property(e => e.ReportUserName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Smtpserver)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("SMTPServer");
            entity.Property(e => e.SqlerrorEmailAddress)
                .HasMaxLength(500)
                .HasColumnName("SQLErrorEmailAddress");
            entity.Property(e => e.SqlerrorMobile)
                .HasMaxLength(500)
                .HasColumnName("SQLErrorMobile");
            entity.Property(e => e.StaffImageDirectory)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StatementBccEmailAddress).HasMaxLength(500);
            entity.Property(e => e.StatementDirectory).HasMaxLength(500);
            entity.Property(e => e.StatementEmailAddress).HasMaxLength(100);
            entity.Property(e => e.StatementOutputDirectory).HasMaxLength(200);
            entity.Property(e => e.StatementReport).HasMaxLength(500);
            entity.Property(e => e.StatementSubject).HasMaxLength(200);
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ToolTipImageDirectory)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TrackAndTrackReplyFromEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UncheckDirectEmailMessage)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.UncheckDirectEmailReply)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UncheckDirectEmailSubject)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UtadditionalFileImageDirectory)
                .HasMaxLength(100)
                .HasColumnName("UTAdditionalFileImageDirectory");
            entity.Property(e => e.UtadditionalFileStyleDirectory)
                .HasMaxLength(100)
                .HasColumnName("UTAdditionalFileStyleDirectory");
            entity.Property(e => e.UtlogoImagePath)
                .HasMaxLength(100)
                .HasColumnName("UTLogoImagePath");
            entity.Property(e => e.UtstyleSheetPath)
                .HasMaxLength(100)
                .HasColumnName("UTStyleSheetPath");
            entity.Property(e => e.Version)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.XeroServiceRefreshToken).HasMaxLength(200);
        });

        modelBuilder.Entity<TblUser>(entity =>
        {
            entity.HasKey(e => e.UserName);

            entity.ToTable("tblUser");

            entity.HasIndex(e => e.CourierId, "CourierID");

            entity.HasIndex(e => e.FullName, "IX_tblUser_FullName").IsUnique();

            entity.HasIndex(e => e.StaffId, "StaffID");

            entity.HasIndex(e => e.UserGroupId, "UserGroupID");

            entity.Property(e => e.UserName).HasMaxLength(50);
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastAccessed).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Notes).HasColumnType("ntext");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.UserGroupId).HasColumnName("UserGroupID");

            entity.HasOne(d => d.Courier).WithMany(p => p.TblUsers)
                .HasForeignKey(d => d.CourierId)
                .HasConstraintName("FK_tblUser_tucCourier");
        });

        modelBuilder.Entity<TucClient>(entity =>
        {
            entity.HasKey(e => e.UcclId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucClient", tb =>
                {
                    tb.HasTrigger("UTL_trgClient_Update");
                    tb.HasTrigger("tucClient_Insert");
                });

            entity.HasIndex(e => e.UcclCode, "IDX_tucClient_ucclCode")
                .IsUnique()
                .HasFillFactor(80);

            entity.HasIndex(e => e.InvoiceScheduleId, "IX_InvoiceScheduleId");

            entity.HasIndex(e => e.InvoiceTemplateId, "IX_InvoiceTemplateId");

            entity.HasIndex(e => e.PaymentTermId, "IX_PaymentTermId");

            entity.HasIndex(e => e.XeroId, "IX_XeroId");

            entity.HasIndex(e => e.UcclName, "Name").IsUnique();

            entity.HasIndex(e => e.SiteId, "SiteID");

            entity.HasIndex(e => e.UtaddtionalItemRateCodeId, "UTAddtionalItemRateCodeID");

            entity.HasIndex(e => e.UtrateCodeId, "UTRateCodeID");

            entity.HasIndex(e => e.UcclBillingType, "ucclBillingType");

            entity.HasIndex(e => e.UcclIndustry, "ucclIndustry");

            entity.HasIndex(e => e.UcclSuburbId, "ucclSuburbID").HasFillFactor(80);

            entity.Property(e => e.UcclId).HasColumnName("ucclID");
            entity.Property(e => e.AccountProfileId).HasColumnName("AccountProfileID");
            entity.Property(e => e.AccountsContact).HasMaxLength(100);
            entity.Property(e => e.AccountsEmail).HasMaxLength(500);
            entity.Property(e => e.AccountsPhone).HasMaxLength(100);
            entity.Property(e => e.AddonPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.AddressExtras).HasMaxLength(200);
            entity.Property(e => e.AddressLine1).HasMaxLength(255);
            entity.Property(e => e.AddressLine2).HasMaxLength(255);
            entity.Property(e => e.AddressLine3).HasMaxLength(255);
            entity.Property(e => e.AddressLine4).HasMaxLength(255);
            entity.Property(e => e.AddressLine5).HasMaxLength(255);
            entity.Property(e => e.AddressLine6).HasMaxLength(255);
            entity.Property(e => e.AddressLine7).HasMaxLength(255);
            entity.Property(e => e.AddressLine8).HasMaxLength(255);
            entity.Property(e => e.AddressStreetName).HasMaxLength(200);
            entity.Property(e => e.AirNzknownShipper).HasColumnName("AirNZKnownShipper");
            entity.Property(e => e.AirNzmargin)
                .HasDefaultValue(0.57m)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("AirNZMargin");
            entity.Property(e => e.ApplyCitySurcharge).HasDefaultValue(true);
            entity.Property(e => e.BaggageRateCodeId).HasColumnName("BaggageRateCodeID");
            entity.Property(e => e.BulkAternoonHomePickupTime).HasColumnType("datetime");
            entity.Property(e => e.BulkHomeDeliveryPickupRateId).HasColumnName("BulkHomeDeliveryPickupRateID");
            entity.Property(e => e.BulkHomeDeliveryVanItemSurcharge).HasColumnType("money");
            entity.Property(e => e.ChilledTruckExcessZoneRateCodeId).HasColumnName("ChilledTruckExcessZoneRateCodeID");
            entity.Property(e => e.ChilledTruckHireRateCodeId).HasColumnName("ChilledTruckHireRateCodeID");
            entity.Property(e => e.ChilledTruckRateCodeId).HasColumnName("ChilledTruckRateCodeID");
            entity.Property(e => e.ChilledVanHireRateCodeId).HasColumnName("ChilledVanHireRateCodeID");
            entity.Property(e => e.CitySurchargeRate)
                .HasDefaultValue(1.75m)
                .HasColumnType("money");
            entity.Property(e => e.CommissionDate).HasColumnType("datetime");
            entity.Property(e => e.CourierPercentage).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.CreateBulkHomeDeliveryPickup).HasDefaultValue(false);
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DangerousServiceRateCodeId).HasColumnName("DangerousServiceRateCodeID");
            entity.Property(e => e.DeliverDifferent).HasDefaultValue(false);
            entity.Property(e => e.DgdryIce)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("DGDryIce");
            entity.Property(e => e.Dgfee)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("DGFee");
            entity.Property(e => e.Discount).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.DropoffReport).HasMaxLength(10);
            entity.Property(e => e.EconomyFlightMarkup).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EconomyFlightOffPeak1RateId).HasColumnName("EconomyFlightOffPeak1RateID");
            entity.Property(e => e.EconomyFlightOffPeak2RateId).HasColumnName("EconomyFlightOffPeak2RateID");
            entity.Property(e => e.EconomyFlightOffPeak3RateId).HasColumnName("EconomyFlightOffPeak3RateID");
            entity.Property(e => e.EconomyFlightOffPeak4RateId).HasColumnName("EconomyFlightOffPeak4RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg1rateId).HasColumnName("EconomyFlightOffPeakKG1RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg2rateId).HasColumnName("EconomyFlightOffPeakKG2RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg3rateId).HasColumnName("EconomyFlightOffPeakKG3RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg4rateId).HasColumnName("EconomyFlightOffPeakKG4RateID");
            entity.Property(e => e.EconomyFlightPeak1RateId).HasColumnName("EconomyFlightPeak1RateID");
            entity.Property(e => e.EconomyFlightPeak2RateId).HasColumnName("EconomyFlightPeak2RateID");
            entity.Property(e => e.EconomyFlightPeak3RateId).HasColumnName("EconomyFlightPeak3RateID");
            entity.Property(e => e.EconomyFlightPeak4RateId).HasColumnName("EconomyFlightPeak4RateID");
            entity.Property(e => e.EconomyFlightPeakKg1rateId).HasColumnName("EconomyFlightPeakKG1RateID");
            entity.Property(e => e.EconomyFlightPeakKg2rateId).HasColumnName("EconomyFlightPeakKG2RateID");
            entity.Property(e => e.EconomyFlightPeakKg3rateId).HasColumnName("EconomyFlightPeakKG3RateID");
            entity.Property(e => e.EconomyFlightPeakKg4rateId).HasColumnName("EconomyFlightPeakKG4RateID");
            entity.Property(e => e.EconomyMinimumJobRateCodeId).HasColumnName("EconomyMinimumJobRateCodeID");
            entity.Property(e => e.EconomyRateCodeId).HasColumnName("EconomyRateCodeID");
            entity.Property(e => e.EconomyRun1).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun2).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun3).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun4).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun5).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun6).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun7).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun8).HasColumnType("datetime");
            entity.Property(e => e.EconomyRunItemsExcessRateCodeId).HasColumnName("EconomyRunItemsExcessRateCodeID");
            entity.Property(e => e.EconomyRunRateCodeId).HasColumnName("EconomyRunRateCodeID");
            entity.Property(e => e.ExpressRateCodeId).HasColumnName("ExpressRateCodeID");
            entity.Property(e => e.FastPalletExpressRateCodeId).HasColumnName("FastPalletExpressRateCodeID");
            entity.Property(e => e.FastPalletStandardRateCodeId).HasColumnName("FastPalletStandardRateCodeID");
            entity.Property(e => e.FastPalletSuperRateCodeId).HasColumnName("FastPalletSuperRateCodeID");
            entity.Property(e => e.FastParcelRateCodeId).HasColumnName("FastParcelRateCodeID");
            entity.Property(e => e.FrozenTruckExcessZoneRateCodeId).HasColumnName("FrozenTruckExcessZoneRateCodeID");
            entity.Property(e => e.FrozenTruckHireRateCodeId).HasColumnName("FrozenTruckHireRateCodeID");
            entity.Property(e => e.FrozenTruckRateCodeId).HasColumnName("FrozenTruckRateCodeID");
            entity.Property(e => e.GssregularPickupClient)
                .HasDefaultValue(false)
                .HasColumnName("GSSRegularPickupClient");
            entity.Property(e => e.GssregularPickupTime)
                .HasColumnType("datetime")
                .HasColumnName("GSSRegularPickupTime");
            entity.Property(e => e.HamiltonDayRunDeliveryRateCodeId).HasColumnName("HamiltonDayRunDeliveryRateCodeID");
            entity.Property(e => e.HamiltonDayRunPurateCodeId).HasColumnName("HamiltonDayRunPURateCodeID");
            entity.Property(e => e.HamiltonNextDayDeliveryRateCodeId).HasColumnName("HamiltonNextDayDeliveryRateCodeID");
            entity.Property(e => e.HamiltonNextDayPurateCodeId).HasColumnName("HamiltonNextDayPURateCodeID");
            entity.Property(e => e.HamiltonRunAdditionalItemsRateCodeId).HasColumnName("HamiltonRunAdditionalItemsRateCodeID");
            entity.Property(e => e.HiabHourRateCodeId).HasColumnName("HiabHourRateCodeID");
            entity.Property(e => e.InternetDisplaySavedJobsAsCombo).HasDefaultValue(true);
            entity.Property(e => e.InternetRebate).HasColumnType("money");
            entity.Property(e => e.InternetShowPickUpLocation).HasDefaultValue(true);
            entity.Property(e => e.Invoice).HasDefaultValue(true);
            entity.Property(e => e.InvoiceEmail).HasMaxLength(500);
            entity.Property(e => e.InvoiceGroupBy).HasMaxLength(50);
            entity.Property(e => e.InvoiceMemo).HasMaxLength(100);
            entity.Property(e => e.InvoiceMethod).HasMaxLength(50);
            entity.Property(e => e.JobPrefix).HasMaxLength(3);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Latitude).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.MarkUp).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MedicalActive).HasDefaultValue(false);
            entity.Property(e => e.MedicalRunAdditionalItemsRateId).HasColumnName("MedicalRunAdditionalItemsRateID");
            entity.Property(e => e.MedicalRunFirstItemRateId).HasColumnName("MedicalRunFirstItemRateID");
            entity.Property(e => e.NextFlight1KgrateId).HasColumnName("NextFlight1KGRateID");
            entity.Property(e => e.NextFlight1RateId).HasColumnName("NextFlight1RateID");
            entity.Property(e => e.NextFlight2KgrateId).HasColumnName("NextFlight2KGRateID");
            entity.Property(e => e.NextFlight2RateId).HasColumnName("NextFlight2RateID");
            entity.Property(e => e.NextFlight3KgrateId).HasColumnName("NextFlight3KGRateID");
            entity.Property(e => e.NextFlight3RateId).HasColumnName("NextFlight3RateID");
            entity.Property(e => e.NextFlight4KgrateId).HasColumnName("NextFlight4KGRateID");
            entity.Property(e => e.NextFlight4RateId).HasColumnName("NextFlight4RateID");
            entity.Property(e => e.NextFlightMarkup).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NoUtpickUp).HasColumnName("NoUTPickUp");
            entity.Property(e => e.NzPostSiteCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OvernightPickupNotRequired).HasDefaultValue(false);
            entity.Property(e => e.OversizeRateCodeId).HasColumnName("OversizeRateCodeID");
            entity.Property(e => e.PpdgraceDays).HasColumnName("PPDGraceDays");
            entity.Property(e => e.Ppdrate)
                .HasDefaultValue(0.05m)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("PPDRate");
            entity.Property(e => e.PrivateAddressSurchargeRateCodeId).HasColumnName("PrivateAddressSurchargeRateCodeID");
            entity.Property(e => e.PromoCode).HasMaxLength(50);
            entity.Property(e => e.PromptForEmailAddress).HasDefaultValue(true);
            entity.Property(e => e.PurchaseOrderNumber).HasMaxLength(100);
            entity.Property(e => e.RateRr).HasColumnName("RateRR");
            entity.Property(e => e.RateShortRr)
                .HasDefaultValue(52)
                .HasColumnName("RateShortRR");
            entity.Property(e => e.ReferenceAdefineList).HasColumnName("ReferenceADefineList");
            entity.Property(e => e.ReferenceAmandatory).HasColumnName("ReferenceAMandatory");
            entity.Property(e => e.ReferenceAmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceAMessage");
            entity.Property(e => e.ReferenceBdefineList).HasColumnName("ReferenceBDefineList");
            entity.Property(e => e.ReferenceBmandatory).HasColumnName("ReferenceBMandatory");
            entity.Property(e => e.ReferenceBmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceBMessage");
            entity.Property(e => e.ReferenceCdefineList).HasColumnName("ReferenceCDefineList");
            entity.Property(e => e.ReferenceCmandatory).HasColumnName("ReferenceCMandatory");
            entity.Property(e => e.ReferenceCmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceCMessage");
            entity.Property(e => e.RerateJobs).HasDefaultValue(true);
            entity.Property(e => e.RuralDeliveryRateCodeId).HasColumnName("RuralDeliveryRateCodeID");
            entity.Property(e => e.Sddenabled)
                .HasDefaultValue(true)
                .HasColumnName("SDDEnabled");
            entity.Property(e => e.Sdrenabled)
                .HasDefaultValue(true)
                .HasColumnName("SDREnabled");
            entity.Property(e => e.ShowNwflight)
                .HasDefaultValue(true)
                .HasColumnName("ShowNWFlight");
            entity.Property(e => e.SigRequiredDefault).HasMaxLength(500);
            entity.Property(e => e.SiteId).HasColumnName("SiteID");
            entity.Property(e => e.SiteUrl)
                .HasMaxLength(500)
                .HasColumnName("SiteURL");
            entity.Property(e => e.Smsname)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("SMSName");
            entity.Property(e => e.StartingWeightExcess).HasDefaultValue(30);
            entity.Property(e => e.StripeClientId)
                .HasMaxLength(50)
                .HasColumnName("StripeClientID");
            entity.Property(e => e.TailLiftRateCodeId).HasColumnName("TailLiftRateCodeID");
            entity.Property(e => e.TrackingEta).HasColumnName("TrackingETA");
            entity.Property(e => e.TruckBulkRateCodeId).HasColumnName("TruckBulkRateCodeID");
            entity.Property(e => e.TruckCitySurchargeRate)
                .HasDefaultValue(10m)
                .HasColumnType("money");
            entity.Property(e => e.TruckEconomyExcessZoneRateCodeId).HasColumnName("TruckEconomyExcessZoneRateCodeID");
            entity.Property(e => e.TruckEconomyRateCodeId).HasColumnName("TruckEconomyRateCodeID");
            entity.Property(e => e.TruckExcessPalletEconomyRateCodeId).HasColumnName("TruckExcessPalletEconomyRateCodeID");
            entity.Property(e => e.TruckExcessPalletFastRateCodeId).HasColumnName("TruckExcessPalletFastRateCodeID");
            entity.Property(e => e.TruckExcessPalletSlowRateCodeId).HasColumnName("TruckExcessPalletSlowRateCodeID");
            entity.Property(e => e.TruckExcessPalletSuperRateCodeId).HasColumnName("TruckExcessPalletSuperRateCodeID");
            entity.Property(e => e.TruckExcessWeightFastRateCodeId).HasColumnName("TruckExcessWeightFastRateCodeID");
            entity.Property(e => e.TruckExcessWeightSlowRateCodeId).HasColumnName("TruckExcessWeightSlowRateCodeID");
            entity.Property(e => e.TruckExcessZoneRateCodeId).HasColumnName("TruckExcessZoneRateCodeID");
            entity.Property(e => e.TruckExpressExcessZoneRateCodeId).HasColumnName("TruckExpressExcessZoneRateCodeID");
            entity.Property(e => e.TruckRateCodeId).HasColumnName("TruckRateCodeID");
            entity.Property(e => e.TruckRoadRateCodeId).HasColumnName("TruckRoadRateCodeID");
            entity.Property(e => e.TruckStandardExcessZoneRateCodeId).HasColumnName("TruckStandardExcessZoneRateCodeID");
            entity.Property(e => e.TruckSuperExcessZoneRateCodeId).HasColumnName("TruckSuperExcessZoneRateCodeID");
            entity.Property(e => e.UcclAccountStatus).HasColumnName("ucclAccountStatus");
            entity.Property(e => e.UcclActive)
                .HasDefaultValue(true)
                .HasColumnName("ucclActive");
            entity.Property(e => e.UcclAddress)
                .HasMaxLength(150)
                .HasColumnName("ucclAddress");
            entity.Property(e => e.UcclAverageDaily)
                .HasDefaultValue(0m)
                .HasColumnType("money")
                .HasColumnName("ucclAverageDaily");
            entity.Property(e => e.UcclAverageDailyGroup).HasColumnName("ucclAverageDailyGroup");
            entity.Property(e => e.UcclAwesome).HasColumnName("ucclAwesome");
            entity.Property(e => e.UcclBillingType).HasColumnName("ucclBillingType");
            entity.Property(e => e.UcclCash).HasColumnName("ucclCash");
            entity.Property(e => e.UcclCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ucclCode");
            entity.Property(e => e.UcclDateJoined)
                .HasColumnType("datetime")
                .HasColumnName("ucclDateJoined");
            entity.Property(e => e.UcclDmfirstName)
                .HasMaxLength(50)
                .HasColumnName("ucclDMFirstName");
            entity.Property(e => e.UcclDmlastName)
                .HasMaxLength(50)
                .HasColumnName("ucclDMLastName");
            entity.Property(e => e.UcclExtraAddress)
                .HasMaxLength(550)
                .HasColumnName("ucclExtraAddress");
            entity.Property(e => e.UcclFax)
                .HasMaxLength(50)
                .HasColumnName("ucclFax");
            entity.Property(e => e.UcclGroupId)
                .HasDefaultValue(0)
                .HasColumnName("ucclGroupID");
            entity.Property(e => e.UcclGstinc).HasColumnName("ucclGSTInc");
            entity.Property(e => e.UcclInActiveDate)
                .HasColumnType("datetime")
                .HasColumnName("ucclInActiveDate");
            entity.Property(e => e.UcclInActiveSetBy)
                .HasMaxLength(50)
                .HasColumnName("ucclInActiveSetBy");
            entity.Property(e => e.UcclIndustry).HasColumnName("ucclIndustry");
            entity.Property(e => e.UcclInternal).HasColumnName("ucclInternal");
            entity.Property(e => e.UcclInternet)
                .HasMaxLength(100)
                .HasColumnName("ucclInternet");
            entity.Property(e => e.UcclLegalName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("ucclLegalName");
            entity.Property(e => e.UcclMcfirstName)
                .HasMaxLength(50)
                .HasColumnName("ucclMCFirstName");
            entity.Property(e => e.UcclMclastName)
                .HasMaxLength(50)
                .HasColumnName("ucclMCLastName");
            entity.Property(e => e.UcclMobile)
                .HasMaxLength(50)
                .HasColumnName("ucclMobile");
            entity.Property(e => e.UcclName)
                .IsRequired()
                .HasMaxLength(75)
                .HasColumnName("ucclName");
            entity.Property(e => e.UcclNote)
                .HasColumnType("ntext")
                .HasColumnName("ucclNote");
            entity.Property(e => e.UcclNotes)
                .HasMaxLength(550)
                .HasColumnName("ucclNotes");
            entity.Property(e => e.UcclPassword)
                .HasMaxLength(50)
                .HasColumnName("ucclPassword");
            entity.Property(e => e.UcclPedal).HasColumnName("ucclPedal");
            entity.Property(e => e.UcclPhone)
                .HasMaxLength(50)
                .HasColumnName("ucclPhone");
            entity.Property(e => e.UcclPhone2)
                .HasMaxLength(50)
                .HasColumnName("ucclPhone2");
            entity.Property(e => e.UcclPodrequired).HasColumnName("ucclPODRequired");
            entity.Property(e => e.UcclPostCode)
                .HasMaxLength(50)
                .HasColumnName("ucclPostCode");
            entity.Property(e => e.UcclPostal)
                .HasMaxLength(150)
                .HasColumnName("ucclPostal");
            entity.Property(e => e.UcclRate).HasColumnName("ucclRate");
            entity.Property(e => e.UcclRateDoc)
                .HasDefaultValue(69)
                .HasColumnName("ucclRateDoc");
            entity.Property(e => e.UcclRateMainTrunk)
                .HasDefaultValue(70)
                .HasColumnName("ucclRateMainTrunk");
            entity.Property(e => e.UcclRateMainTrunkKg)
                .HasDefaultValue(71)
                .HasColumnName("ucclRateMainTrunkKG");
            entity.Property(e => e.UcclRateNi)
                .HasDefaultValue(67)
                .HasColumnName("ucclRateNI");
            entity.Property(e => e.UcclRateNiweight)
                .HasDefaultValue(74)
                .HasColumnName("ucclRateNIWeight");
            entity.Property(e => e.UcclRateOther)
                .HasDefaultValue(72)
                .HasColumnName("ucclRateOther");
            entity.Property(e => e.UcclRateOtherKg)
                .HasDefaultValue(73)
                .HasColumnName("ucclRateOtherKG");
            entity.Property(e => e.UcclRateShorthaul)
                .HasDefaultValue(76)
                .HasColumnName("ucclRateShorthaul");
            entity.Property(e => e.UcclRateShorthaulKg)
                .HasDefaultValue(77)
                .HasColumnName("ucclRateShorthaulKG");
            entity.Property(e => e.UcclRateSi)
                .HasDefaultValue(68)
                .HasColumnName("ucclRateSI");
            entity.Property(e => e.UcclRateSiweight)
                .HasDefaultValue(75)
                .HasColumnName("ucclRateSIWeight");
            entity.Property(e => e.UcclReferralNotes)
                .HasColumnType("ntext")
                .HasColumnName("ucclReferralNotes");
            entity.Property(e => e.UcclReferralSource).HasColumnName("ucclReferralSource");
            entity.Property(e => e.UcclSlow).HasColumnName("ucclSlow");
            entity.Property(e => e.UcclStaff).HasColumnName("ucclStaff");
            entity.Property(e => e.UcclSuburbId).HasColumnName("ucclSuburbID");
            entity.Property(e => e.UcclType)
                .HasMaxLength(50)
                .HasColumnName("ucclType");
            entity.Property(e => e.UcclUseGroup).HasColumnName("ucclUseGroup");
            entity.Property(e => e.Ucclemail)
                .HasMaxLength(100)
                .HasColumnName("ucclemail");
            entity.Property(e => e.UrgentTonightCategoryId).HasColumnName("UrgentTonightCategoryID");
            entity.Property(e => e.UrgentTonightLogo).HasMaxLength(500);
            entity.Property(e => e.UrgentTonightSequence).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UrgentTonightStyleSheet).HasMaxLength(500);
            entity.Property(e => e.UtaddtionalItemRateCodeId).HasColumnName("UTAddtionalItemRateCodeID");
            entity.Property(e => e.UtcutOff)
                .HasColumnType("datetime")
                .HasColumnName("UTCutOff");
            entity.Property(e => e.UtminimumJobsAmount)
                .HasColumnType("money")
                .HasColumnName("UTMinimumJobsAmount");
            entity.Property(e => e.UtminimumJobsPerDay).HasColumnName("UTMinimumJobsPerDay");
            entity.Property(e => e.UtpickupTime)
                .HasColumnType("datetime")
                .HasColumnName("UTPickupTime");
            entity.Property(e => e.UtrateCodeId).HasColumnName("UTRateCodeID");
            entity.Property(e => e.WebServicePassword).HasMaxLength(100);
            entity.Property(e => e.XeroId).HasMaxLength(50);
        });

        modelBuilder.Entity<TucClientContact>(entity =>
        {
            entity.HasKey(e => e.UcctId)
                .HasName("PK_tucClientContacts")
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucClientContact", tb => tb.HasTrigger("UTL_trgContact_Update"));

            entity.HasIndex(e => e.ContactRoleId, "ContractRoleID");

            entity.HasIndex(e => e.ParentContactId, "ParentContactID");

            entity.HasIndex(e => e.Password, "Password");

            entity.HasIndex(e => e.UserName, "UserName");

            entity.HasIndex(e => e.UcctClientId, "ucctClientID");

            entity.Property(e => e.UcctId).HasColumnName("ucctID");
            entity.Property(e => e.AccessCode).HasMaxLength(50);
            entity.Property(e => e.ContactRoleId).HasColumnName("ContactRoleID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Fax).HasMaxLength(50);
            entity.Property(e => e.HasEmail).HasDefaultValue(true);
            entity.Property(e => e.LastAccessed).HasColumnType("datetime");
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ParentContactId).HasColumnName("ParentContactID");
            entity.Property(e => e.Password).HasMaxLength(50);
            entity.Property(e => e.Password2).HasMaxLength(200);
            entity.Property(e => e.PromptForEmailAddress).HasDefaultValue(true);
            entity.Property(e => e.ResetKey).HasMaxLength(50);
            entity.Property(e => e.Salt).HasMaxLength(64);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.UcctClientId).HasColumnName("ucctClientID");
            entity.Property(e => e.UcctDirectDial)
                .HasMaxLength(50)
                .HasColumnName("ucctDirectDial");
            entity.Property(e => e.UcctEmail)
                .HasMaxLength(200)
                .HasColumnName("ucctEmail");
            entity.Property(e => e.UcctFirstname)
                .HasMaxLength(50)
                .HasColumnName("ucctFirstname");
            entity.Property(e => e.UcctJobTitle)
                .HasMaxLength(50)
                .HasColumnName("ucctJobTitle");
            entity.Property(e => e.UcctMobile)
                .HasMaxLength(50)
                .HasColumnName("ucctMobile");
            entity.Property(e => e.UcctNotes)
                .HasMaxLength(250)
                .HasColumnName("ucctNotes");
            entity.Property(e => e.UcctSurname)
                .HasMaxLength(50)
                .HasColumnName("ucctSurname");
            entity.Property(e => e.UserName).HasMaxLength(200);
            entity.Property(e => e.WhenEmailNotificationSent).HasColumnType("datetime");
            entity.Property(e => e.WhenEmailValidated).HasColumnType("datetime");
            entity.Property(e => e.WhenEmailValidatedSent).HasColumnType("datetime");
            entity.Property(e => e.WhenLastEmailNotificationReminderSent).HasColumnType("datetime");

            entity.HasOne(d => d.UcctClient).WithMany(p => p.TucClientContacts)
                .HasForeignKey(d => d.UcctClientId)
                .HasConstraintName("FK_tucClientContact_tucClient");
        });

        modelBuilder.Entity<TucCourier>(entity =>
        {
            entity.HasKey(e => e.UccrId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucCourier", tb => tb.HasTrigger("UTL_trgCourier_Update"));

            entity.HasIndex(e => e.UccrCarrierLiabilityId, "CarrierLiabilityID");

            entity.HasIndex(e => e.UccrChannelId, "ChannelID");

            entity.HasIndex(e => e.CourierFleetId, "CourierFleetID");

            entity.HasIndex(e => e.CourierGpsid, "CourierGPSID");

            entity.HasIndex(e => e.CourierLogInOutId, "CourierLogInOutID");

            entity.HasIndex(e => e.CourierTypeId, "IX_CourierTypeId");

            entity.HasIndex(e => e.MasterCourierId, "IX_MasterCourierId");

            entity.HasIndex(e => e.RegionId, "IX_RegionId");

            entity.HasIndex(e => e.XeroId, "IX_XeroId");

            entity.HasIndex(e => e.Code, "IX_tucCourier_Code");

            entity.HasIndex(e => new { e.UccrName, e.UccrSurname }, "IX_tucCourier_FullName").IsUnique();

            entity.HasIndex(e => e.UccrInsuranceId, "InsuranceID");

            entity.HasIndex(e => e.UccrPublicLiabilityId, "PublicLiabilityID");

            entity.HasIndex(e => e.Active, "Scan1");

            entity.HasIndex(e => e.SiteId, "SiteID");

            entity.HasIndex(e => e.UccrVehicleMakeId, "VehicleMakeID");

            entity.HasIndex(e => e.CourierFleetId, "uccrType");

            entity.Property(e => e.UccrId).HasColumnName("uccrID");
            entity.Property(e => e.AccountProfileId).HasColumnName("AccountProfileID");
            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.AddressLine1).HasMaxLength(255);
            entity.Property(e => e.AddressLine2).HasMaxLength(255);
            entity.Property(e => e.AddressLine3).HasMaxLength(255);
            entity.Property(e => e.AddressLine4).HasMaxLength(255);
            entity.Property(e => e.AddressLine5).HasMaxLength(255);
            entity.Property(e => e.AddressLine6).HasMaxLength(255);
            entity.Property(e => e.AddressLine7).HasMaxLength(255);
            entity.Property(e => e.AddressLine8).HasMaxLength(255);
            entity.Property(e => e.AfterHoursWeb).HasDefaultValue(false);
            entity.Property(e => e.AutoDespatch).HasDefaultValue(true);
            entity.Property(e => e.BankRoutingNumber).HasMaxLength(9);
            entity.Property(e => e.BaseVehicle).HasDefaultValue(false);
            entity.Property(e => e.Blurb).HasMaxLength(1000);
            entity.Property(e => e.BonusPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.CarSavingsAmount).HasColumnType("money");
            entity.Property(e => e.CarSavingsEnd).HasColumnType("datetime");
            entity.Property(e => e.CarSavingsStart).HasColumnType("datetime");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CourierFleetId).HasColumnName("CourierFleetID");
            entity.Property(e => e.CourierGpsid).HasColumnName("CourierGPSID");
            entity.Property(e => e.CourierLogInOutId).HasColumnName("CourierLogInOutID");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DeviceTypeId)
                .HasDefaultValue(1)
                .HasColumnName("DeviceTypeID");
            entity.Property(e => e.DglicenseExpiry)
                .HasColumnType("datetime")
                .HasColumnName("DGLicenseExpiry");
            entity.Property(e => e.DriversLicenseExpiry).HasColumnType("datetime");
            entity.Property(e => e.ExpectedEndTime).HasColumnType("datetime");
            entity.Property(e => e.ExpectedStartTime).HasColumnType("datetime");
            entity.Property(e => e.JobPaperPrintOut).HasDefaultValue(true);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Macourier).HasColumnName("MACourier");
            entity.Property(e => e.MaxPallets).HasDefaultValue(1);
            entity.Property(e => e.MaxPayload).HasDefaultValue(1000.0);
            entity.Property(e => e.MobileAdAmount).HasColumnType("money");
            entity.Property(e => e.MobileAdEnd).HasColumnType("datetime");
            entity.Property(e => e.MobileAdStart).HasColumnType("datetime");
            entity.Property(e => e.MobileInsurance)
                .HasDefaultValue(0.00m)
                .HasColumnType("money");
            entity.Property(e => e.MobileRental)
                .HasDefaultValue(0.00m)
                .HasColumnType("money");
            entity.Property(e => e.OpenForceNumber).HasMaxLength(50);
            entity.Property(e => e.PaydayFileRegistration).HasDefaultValue(false);
            entity.Property(e => e.PersonalMobile).HasMaxLength(50);
            entity.Property(e => e.Podreqd)
                .HasDefaultValue(false)
                .HasColumnName("PODreqd");
            entity.Property(e => e.RegistrationExpiry).HasColumnType("datetime");
            entity.Property(e => e.Ruckms).HasColumnName("RUCKms");
            entity.Property(e => e.Rucpayload).HasColumnName("RUCPayload");
            entity.Property(e => e.Rucweight).HasColumnName("RUCWeight");
            entity.Property(e => e.SendAlertSms).HasColumnName("SendAlertSMS");
            entity.Property(e => e.SendJobsViaSms).HasColumnName("SendJobsViaSMS");
            entity.Property(e => e.SiteId)
                .HasDefaultValue(1)
                .HasColumnName("SiteID");
            entity.Property(e => e.SubContractorBonusPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.SubContractorFuelPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.SubContractorPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.TaxSavingsEnd).HasColumnType("datetime");
            entity.Property(e => e.TaxSavingsStart).HasColumnType("datetime");
            entity.Property(e => e.TrainingHr).HasMaxLength(50);
            entity.Property(e => e.TrainingHrFu)
                .HasMaxLength(50)
                .HasColumnName("TrainingHrFU");
            entity.Property(e => e.UccrAddress)
                .HasMaxLength(100)
                .HasColumnName("uccrAddress");
            entity.Property(e => e.UccrBankAccountNo)
                .HasMaxLength(50)
                .HasColumnName("uccrBankAccountNo");
            entity.Property(e => e.UccrBankBranch)
                .HasMaxLength(50)
                .HasColumnName("uccrBankBranch");
            entity.Property(e => e.UccrBankNameId).HasColumnName("uccrBankNameID");
            entity.Property(e => e.UccrCarrierLiabilityId).HasColumnName("uccrCarrierLiabilityID");
            entity.Property(e => e.UccrChannelId).HasColumnName("uccrChannelID");
            entity.Property(e => e.UccrContractDate)
                .HasColumnType("datetime")
                .HasColumnName("uccrContractDate");
            entity.Property(e => e.UccrCustomField1)
                .HasMaxLength(50)
                .HasColumnName("uccrCustomField1");
            entity.Property(e => e.UccrCustomField2)
                .HasMaxLength(50)
                .HasColumnName("uccrCustomField2");
            entity.Property(e => e.UccrCustomField3)
                .HasMaxLength(50)
                .HasColumnName("uccrCustomField3");
            entity.Property(e => e.UccrDangerousGoods).HasColumnName("uccrDangerousGoods");
            entity.Property(e => e.UccrDlno)
                .HasMaxLength(50)
                .HasColumnName("uccrDLNo");
            entity.Property(e => e.UccrDob)
                .HasColumnType("datetime")
                .HasColumnName("uccrDOB");
            entity.Property(e => e.UccrDoctor)
                .HasMaxLength(50)
                .HasColumnName("uccrDoctor");
            entity.Property(e => e.UccrDoctorPhone)
                .HasMaxLength(50)
                .HasColumnName("uccrDoctorPhone");
            entity.Property(e => e.UccrEmail)
                .HasMaxLength(100)
                .HasColumnName("uccrEmail");
            entity.Property(e => e.UccrFinishDate)
                .HasColumnType("datetime")
                .HasColumnName("uccrFinishDate");
            entity.Property(e => e.UccrGsl)
                .HasMaxLength(50)
                .HasColumnName("uccrGSL");
            entity.Property(e => e.UccrGst)
                .HasMaxLength(50)
                .HasColumnName("uccrGST");
            entity.Property(e => e.UccrInsuranceId).HasColumnName("uccrInsuranceID");
            entity.Property(e => e.UccrInternal).HasColumnName("uccrInternal");
            entity.Property(e => e.UccrKinAdd)
                .HasMaxLength(100)
                .HasColumnName("uccrKinAdd");
            entity.Property(e => e.UccrKinName)
                .HasMaxLength(50)
                .HasColumnName("uccrKinName");
            entity.Property(e => e.UccrKinRelationship)
                .HasMaxLength(50)
                .HasColumnName("uccrKinRelationship");
            entity.Property(e => e.UccrKinTel)
                .HasMaxLength(50)
                .HasColumnName("uccrKinTel");
            entity.Property(e => e.UccrLate).HasColumnName("uccrLate");
            entity.Property(e => e.UccrMobile)
                .HasMaxLength(50)
                .HasColumnName("uccrMobile");
            entity.Property(e => e.UccrName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("uccrName");
            entity.Property(e => e.UccrNotes)
                .HasColumnType("ntext")
                .HasColumnName("uccrNotes");
            entity.Property(e => e.UccrPagerId).HasColumnName("uccrPagerID");
            entity.Property(e => e.UccrPagerSerial)
                .HasMaxLength(50)
                .HasColumnName("uccrPagerSerial");
            entity.Property(e => e.UccrPassword)
                .HasMaxLength(50)
                .HasColumnName("uccrPassword");
            entity.Property(e => e.UccrPercentage).HasColumnName("uccrPercentage");
            entity.Property(e => e.UccrPicturePath)
                .HasMaxLength(500)
                .HasColumnName("uccrPicturePath");
            entity.Property(e => e.UccrPolicyNo)
                .HasMaxLength(50)
                .HasColumnName("uccrPolicy_No");
            entity.Property(e => e.UccrProfile)
                .HasMaxLength(255)
                .HasColumnName("uccrProfile");
            entity.Property(e => e.UccrPublicLiabilityId).HasColumnName("uccrPublicLiabilityID");
            entity.Property(e => e.UccrReg)
                .HasMaxLength(50)
                .HasColumnName("uccrReg");
            entity.Property(e => e.UccrRt)
                .HasMaxLength(50)
                .HasColumnName("uccrRT");
            entity.Property(e => e.UccrRtaddress)
                .HasMaxLength(50)
                .HasColumnName("uccrRTAddress");
            entity.Property(e => e.UccrSecurityDate)
                .HasColumnType("datetime")
                .HasColumnName("uccrSecurityDate");
            entity.Property(e => e.UccrShowClientPh).HasColumnName("uccrShowClientPh");
            entity.Property(e => e.UccrStartDate)
                .HasColumnType("datetime")
                .HasColumnName("uccrStartDate");
            entity.Property(e => e.UccrSurname)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("uccrSurname");
            entity.Property(e => e.UccrTeam).HasColumnName("uccrTeam");
            entity.Property(e => e.UccrTel)
                .HasMaxLength(50)
                .HasColumnName("uccrTel");
            entity.Property(e => e.UccrVehicle)
                .HasMaxLength(50)
                .HasColumnName("uccrVehicle");
            entity.Property(e => e.UccrVehicleMakeId).HasColumnName("uccrVehicleMakeID");
            entity.Property(e => e.UccrVehicleModel)
                .HasMaxLength(50)
                .HasColumnName("uccrVehicleModel");
            entity.Property(e => e.UccrVehicleYear).HasColumnName("uccrVehicleYear");
            entity.Property(e => e.UccrWebEnabled).HasColumnName("uccrWebEnabled");
            entity.Property(e => e.VehiclePlateNnumber)
                .HasMaxLength(50)
                .HasColumnName("VehiclePlateNNumber");
            entity.Property(e => e.VehicleVinnumber)
                .HasMaxLength(255)
                .HasColumnName("VehicleVINNumber");
            entity.Property(e => e.WithholdingTaxPercentage)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(8, 2)");
            entity.Property(e => e.Wofexpiry)
                .HasColumnType("datetime")
                .HasColumnName("WOFExpiry");
            entity.Property(e => e.XeroId).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}