// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Hub.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Hub.Models
{
    public partial class DespatchContext
    {
        private IDespatchContextProcedures _procedures;

        public virtual IDespatchContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DespatchContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDespatchContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DespatchContextProcedures : IDespatchContextProcedures
    {
        private readonly DespatchContext _context;

        public DespatchContextProcedures(DespatchContext context)
        {
            _context = context;
        }

        public virtual async Task<int> NET_stpContact_ResetPasswordAsync(int? ContactID, string RecoveryEmail, string ReplyEmail, string Link, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContactID",
                    Value = ContactID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "RecoveryEmail",
                    Size = 300,
                    Value = RecoveryEmail ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ReplyEmail",
                    Size = 300,
                    Value = ReplyEmail ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Link",
                    Size = 1000,
                    Value = Link ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[NET_stpContact_ResetPassword] @ContactID = @ContactID, @RecoveryEmail = @RecoveryEmail, @ReplyEmail = @ReplyEmail, @Link = @Link", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<RVW_stpValidateClientResult>> RVW_stpValidateClientAsync(int? ClientID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientID",
                    Value = ClientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<RVW_stpValidateClientResult>("EXEC @returnValue = [dbo].[RVW_stpValidateClient] @ClientID = @ClientID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<RVW_stpValidateContactResult>> RVW_stpValidateContactAsync(int? ContactID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContactID",
                    Value = ContactID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<RVW_stpValidateContactResult>("EXEC @returnValue = [dbo].[RVW_stpValidateContact] @ContactID = @ContactID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<RVW_stpValidateInternetPermissionsResult>> RVW_stpValidateInternetPermissionsAsync(int? ContactID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContactID",
                    Value = ContactID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<RVW_stpValidateInternetPermissionsResult>("EXEC @returnValue = [dbo].[RVW_stpValidateInternetPermissions] @ContactID = @ContactID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
