// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class Feature
{
    public string FeatureKey { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    // Release state (tile-level direction, 2026-08-26). A feature reaches a
    // tenant only when ClientVisible AND ReleaseStatus == "Live". Added by
    // dbmigrationsv2 20260826170000_FeatureReleaseState.sql - that migration
    // MUST be applied to a tenant DB before this app is deployed against it,
    // or EF selects columns that do not exist.
    public bool ClientVisible { get; set; }

    public string ReleaseStatus { get; set; }

    // Country scope (SEED-SCOPE-ALL-HUBS §2). Comma-separated ISO codes; NULL
    // or empty means available everywhere. Set from the configurator's Feature
    // Matrix. Hub did not carry this column, so a feature scoped to one market
    // was filtered out of the configurator's sidebar while its hub tile still
    // rendered here - the two resolvers disagreeing in exactly the way the
    // comments on FeatureResolver warn about.
    public string AvailableCountries { get; set; }

    public virtual ICollection<ClientTypeFeature> ClientTypeFeatures { get; set; } = new List<ClientTypeFeature>();
}