// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Hub.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Hub.Models
{
    public partial interface IDespatchContextProcedures
    {
        Task<int> NET_stpContact_ResetPasswordAsync(int? ContactID, string RecoveryEmail, string ReplyEmail, string Link, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RVW_stpValidateClientResult>> RVW_stpValidateClientAsync(int? ClientID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RVW_stpValidateContactResult>> RVW_stpValidateContactAsync(int? ContactID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RVW_stpValidateInternetPermissionsResult>> RVW_stpValidateInternetPermissionsAsync(int? ContactID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
