// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UrgentHub.Models
{
    public partial class RVW_stpValidateInternetPermissionsResult
    {
        public int InternetPermissionID { get; set; }
        public int ClientContactID { get; set; }
    }
}
