// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hub.Models
{
    public partial class RVW_stpValidateContactResult
    {
        public int? ClientID { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string UserName { get; set; }
        public DateTime Created { get; set; }
        public int? ContactCount { get; set; }
    }
}
