// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hub.Models
{
    public partial class RVW_stpValidateClientResult
    {
        [StringLength(75)]
        public string Name { get; set; }
        public bool Active { get; set; }
        public bool Internal { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(100)]
        public string WebServicePassword { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public DateTime Created { get; set; }
        public bool StripeClient { get; set; }
    }
}
