// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class TblAfterhoursCourier
{
    public int Id { get; set; }

    public int CourierId { get; set; }

    public int WeekDay { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public virtual TucCourier Courier { get; set; }
}