// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class TblFuelSurcharge
{
    public int FuelSurchargeId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public int? ClientId { get; set; }

    public DateTime Start { get; set; }

    public DateTime? End { get; set; }

    public decimal Rate { get; set; }

    public bool Active { get; set; }

    public decimal? PumpPrice { get; set; }

    public int? VehicleSizeId { get; set; }

    public virtual TucClient Client { get; set; }
}