// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class TblSetting
{
    public int SettingId { get; set; }

    public int MaxAutoLatePickupAlert { get; set; }

    public int MaxAutoLateDeliveryAlert { get; set; }

    public int EntryFormCount { get; set; }

    public string SystemName { get; set; }

    public string Version { get; set; }

    public string ApplicationName { get; set; }

    public string AdminEmail { get; set; }

    public string ReportUserName { get; set; }

    public string ReportPassword { get; set; }

    public string ReportDomain { get; set; }

    public int ReportTimeout { get; set; }

    public string DefaultDateRange { get; set; }

    public string EnquiryEmail { get; set; }

    public string Smtpserver { get; set; }

    public string ContactUsEmailSubject { get; set; }

    public int DefaultPageDisplayNewsItems { get; set; }

    public int NewsPageDisplayItems { get; set; }

    public int CustomerFeedbackPageDisplayItems { get; set; }

    public int CustomerFeedbackPageDisplayCharacters { get; set; }

    public string NewsImageDirectory { get; set; }

    public string StaffImageDirectory { get; set; }

    public string CommunicationFileDirectory { get; set; }

    public string JoinOurTeamEmail { get; set; }

    public string JoinOurTeamSubject { get; set; }

    public string JobFeedbackSubject { get; set; }

    public int InternetJobChargeType { get; set; }

    public int InternetJobStaffId { get; set; }

    public string InternetJobEmailSubject { get; set; }

    public string InternetJobPoaemail { get; set; }

    public string InternetJobPoaemailSubject { get; set; }

    public int NationwideAreaId { get; set; }

    public string ToolTipImageDirectory { get; set; }

    public int DefaultPageDisplayJobItems { get; set; }

    public int InternetInvoiceReportId { get; set; }

    public string InternetRoot { get; set; }

    public string InternetClientDetailsEmail { get; set; }

    public string InternetClientDetailsSubject { get; set; }

    public string JoinOurTeamReplyFromEmail { get; set; }

    public string JoinOurTeamReplySubject { get; set; }

    public string JoinOurTeamReplyMessage { get; set; }

    public string JoinOurTeamReplyAttachment { get; set; }

    public byte[] FaxHeadLogo { get; set; }

    public byte[] LetterHeadLogo { get; set; }

    public int InternetRateScheduleReportId { get; set; }

    public string JobDetailsReplyFromEmail { get; set; }

    public string TrackAndTrackReplyFromEmail { get; set; }

    public int? RateGuideCommunicationTypeId { get; set; }

    public string SqlerrorEmailAddress { get; set; }

    public string SqlerrorMobile { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public string ComposerExtrasPath { get; set; }

    public string StatementMessage { get; set; }

    public string StatementReport { get; set; }

    public string JournalEntityCode { get; set; }

    public string JournalTransactionCode { get; set; }

    public string JournalCreatedBy { get; set; }

    public string JournalNarration { get; set; }

    public string StatementEmailAddress { get; set; }

    public bool DespatchCheckContactHasEmail { get; set; }

    public string GstregistrationNumber { get; set; }

    public string CompanyBankNumber { get; set; }

    public string CompanyAddress { get; set; }

    public string ReportFolder { get; set; }

    public string ReportServicesUrl { get; set; }

    public int InternetStatementReportId { get; set; }

    public byte[] FaxHeadLogoSmall { get; set; }

    public int StatementCountPerGroup { get; set; }

    public string StatementOutputDirectory { get; set; }

    public int StatementDelayBetweenGroups { get; set; }

    public string MapRoot { get; set; }

    public string DespatchUniqueEmailNotifyAddress { get; set; }

    public int? CurrentLoading { get; set; }

    public bool AutomaticUpdateLoading { get; set; }

    public string UncheckDirectEmailMessage { get; set; }

    public string UncheckDirectEmailSubject { get; set; }

    public string UncheckDirectEmailReply { get; set; }

    public int? BurstTheBubbleCourierId { get; set; }

    public string RatesGuideImagePath { get; set; }

    public string GoogleMapApikey { get; set; }

    public bool AllowPostingToOa { get; set; }

    public string UtlogoImagePath { get; set; }

    public string UtstyleSheetPath { get; set; }

    public string UtadditionalFileStyleDirectory { get; set; }

    public string UtadditionalFileImageDirectory { get; set; }

    public bool? UseGoogleAnalytics { get; set; }

    public string GoogleAnalyticsCode { get; set; }

    public int? JobPackingReportId { get; set; }

    public string DataComClientId { get; set; }

    public int? ParentJobCourierId { get; set; }

    public string GoogleMapRoot { get; set; }

    public string DpspayRoot { get; set; }

    public int? InternetInvoiceSignatureReportId { get; set; }

    public decimal? Gstrate { get; set; }

    public string AddressValidationUrl { get; set; }

    public string AddressValidationUser { get; set; }

    public string AddressValidationPass { get; set; }

    public bool? AddressValidationActive { get; set; }

    public string GoogleMapGeneratorRoot { get; set; }

    public bool? GoogleSmtpserverActive { get; set; }

    public string GoogleSmtpserver { get; set; }

    public string GoogleSmtpserverUser { get; set; }

    public string GoogleSmtpserverPass { get; set; }

    public bool? AddressValidationDespatchActive { get; set; }

    public bool? AddressValidationActiveMercury { get; set; }

    public bool? GooglePlaceAutocompleteActive { get; set; }

    public string GooglePlaceAutocompleteApikey { get; set; }

    public string XeroServiceRefreshToken { get; set; }

    public DateTime? LastJobArchive { get; set; }

    public long? QuickBooksRealmId { get; set; }

    public string QuickBooksRefreshToken { get; set; }

    public DateTime? AccountsStartDate { get; set; }

    public string PpdCode { get; set; }

    public string PpdDescription { get; set; }

    public string PpdAppliedDescription { get; set; }

    public bool PpdGroupByLocation { get; set; }

    public int? AccountsClientDefaultId { get; set; }

    public int? InvoiceTemplateId { get; set; }

    public string StatementBccEmailAddress { get; set; }

    public string StatementDirectory { get; set; }

    public bool? StatementMessageIsHtml { get; set; }

    public string OpenforceClientId { get; set; }

    public string OpenforceAccessKey { get; set; }

    public string OpenforceActivationCode { get; set; }

    public int? AccountsMode { get; set; }

    public string OpenforceApiKey { get; set; }

    public string OpenforceClientGuid { get; set; }

    public string ReceivableAccount { get; set; }

    public string StatementSubject { get; set; }

    public DateTime? CourierServiceProcessed { get; set; }

    public string InvoiceMemo { get; set; }

    public int? PaymentTermId { get; set; }

    public bool? InvoiceUseCalendarMonth { get; set; }

    public string PpdItemCode { get; set; }

    public double? DefaultCourierPercentage { get; set; }

    public decimal? DefaultCourierWithholdingTaxPercentage { get; set; }

    public string DefaultRevenueAccount { get; set; }

    public string DefaultClass { get; set; }

    public string DefaultItemCode { get; set; }

    public string DefaultItemCodeFuel { get; set; }

    public string AccountsRefreshToken { get; set; }

    public string AccountsTenantId { get; set; }

    public string AccountsCodePpd { get; set; }

    public string AccountsDescriptionPpd { get; set; }

    public bool? AccountsGroupBySitePpd { get; set; }

    public string AccountsCodeBonus { get; set; }

    public string AccountsItemCodeBonus { get; set; }

    public bool AccountsGroupByLocationBonus { get; set; }

    public string AccountsDescriptionBonus { get; set; }

    public int? DefaultJobLabelId { get; set; }

    public int? DefaultBulkLabelId { get; set; }

    public string CountryCode { get; set; }
}