//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace UrgentHub.Models
{
	/// <summary>Class which represents the entity 'TblUser'.</summary>
	public partial class TblUser : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblUser"/> class.</summary>
		public TblUser() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Active field. </summary>
		public System.Boolean Active { get; set; }
		/// <summary>Gets or sets the CourierId field. </summary>
		public Nullable<System.Int32> CourierId { get; set; }
		/// <summary>Gets or sets the CourierSecurity field. </summary>
		public System.Boolean CourierSecurity { get; set; }
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set; }
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set; }
		/// <summary>Gets or sets the FullName field. </summary>
		public System.String FullName { get; set; }
		/// <summary>Gets or sets the InternetAccess field. </summary>
		public System.Boolean InternetAccess { get; set; }
		/// <summary>Gets or sets the LastAccessed field. </summary>
		public Nullable<System.DateTime> LastAccessed { get; set; }
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set; }
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set; }
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set; }
		/// <summary>Gets or sets the Password field. </summary>
		public System.String Password { get; set; }
		/// <summary>Gets or sets the StaffId field. </summary>
		public Nullable<System.Int32> StaffId { get; set; }
		/// <summary>Gets or sets the UserGroupId field. </summary>
		public System.Int32 UserGroupId { get; set; }
		/// <summary>Gets or sets the UserName field. </summary>
		public System.String UserName { get; set; }
	}
}
