// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class TblUser
{
    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public int UserGroupId { get; set; }

    public DateTime? LastAccessed { get; set; }

    public bool Active { get; set; }

    public bool CourierSecurity { get; set; }

    public int? CourierId { get; set; }

    public int? StaffId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public bool InternetAccess { get; set; }

    public virtual TucCourier Courier { get; set; }
}