//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace UrgentHub.Models
{
	/// <summary>Class which represents the entity 'TucClient'.</summary>
	public partial class TucClient : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucClient"/> class.</summary>
		public TucClient() : base()
		{
			this.TucClientContacts = new List<TucClientContact>();
			OnCreated();
		}

		/// <summary>Gets or sets the AccountProfileId field. </summary>
		public Nullable<System.Int32> AccountProfileId { get; set; }
		/// <summary>Gets or sets the AddonPercentage field. </summary>
		public Nullable<System.Decimal> AddonPercentage { get; set; }
		/// <summary>Gets or sets the AddressExtras field. </summary>
		public System.String AddressExtras { get; set; }
		/// <summary>Gets or sets the AddressStreetName field. </summary>
		public System.String AddressStreetName { get; set; }
		/// <summary>Gets or sets the AlertLateDelivery field. </summary>
		public System.Int32 AlertLateDelivery { get; set; }
		/// <summary>Gets or sets the AlertLatePickUp field. </summary>
		public System.Int32 AlertLatePickUp { get; set; }
		/// <summary>Gets or sets the ApplyCitySurcharge field. </summary>
		public Nullable<System.Boolean> ApplyCitySurcharge { get; set; }
		/// <summary>Gets or sets the BaggageActive field. </summary>
		public System.Boolean BaggageActive { get; set; }
		/// <summary>Gets or sets the BaggageRateCodeId field. </summary>
		public Nullable<System.Int32> BaggageRateCodeId { get; set; }
		/// <summary>Gets or sets the BulkAternoonHomePickupTime field. </summary>
		public Nullable<System.DateTime> BulkAternoonHomePickupTime { get; set; }
		/// <summary>Gets or sets the BulkHomeDeliveryPickupRateId field. </summary>
		public Nullable<System.Int32> BulkHomeDeliveryPickupRateId { get; set; }
		/// <summary>Gets or sets the BulkHomeDeliveryVanItemExcess field. </summary>
		public Nullable<System.Int32> BulkHomeDeliveryVanItemExcess { get; set; }
		/// <summary>Gets or sets the BulkHomeDeliveryVanItemSurcharge field. </summary>
		public Nullable<System.Decimal> BulkHomeDeliveryVanItemSurcharge { get; set; }
		/// <summary>Gets or sets the BulkMinimumAmount field. </summary>
		public Nullable<System.Double> BulkMinimumAmount { get; set; }
		/// <summary>Gets or sets the CitySurchargeRate field. </summary>
		public Nullable<System.Decimal> CitySurchargeRate { get; set; }
		/// <summary>Gets or sets the CommissionDate field. </summary>
		public Nullable<System.DateTime> CommissionDate { get; set; }
		/// <summary>Gets or sets the CommissionExclude field. </summary>
		public Nullable<System.Boolean> CommissionExclude { get; set; }
		/// <summary>Gets or sets the CourierPercentage field. </summary>
		public Nullable<System.Decimal> CourierPercentage { get; set; }
		/// <summary>Gets or sets the CreateBulkHomeDeliveryPickup field. </summary>
		public Nullable<System.Boolean> CreateBulkHomeDeliveryPickup { get; set; }
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set; }
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set; }
		/// <summary>Gets or sets the DangerousServiceRateCodeId field. </summary>
		public Nullable<System.Int32> DangerousServiceRateCodeId { get; set; }
		/// <summary>Gets or sets the DgdryIce field. </summary>
		public Nullable<System.Decimal> DgdryIce { get; set; }
		/// <summary>Gets or sets the Dgfee field. </summary>
		public Nullable<System.Decimal> Dgfee { get; set; }
		/// <summary>Gets or sets the Discount field. </summary>
		public System.Decimal Discount { get; set; }
		/// <summary>Gets or sets the DisplayRateRef field. </summary>
		public System.Boolean DisplayRateRef { get; set; }
		/// <summary>Gets or sets the DropoffReport field. </summary>
		public System.String DropoffReport { get; set; }
		/// <summary>Gets or sets the EconomyActive field. </summary>
		public System.Boolean EconomyActive { get; set; }
		/// <summary>Gets or sets the EconomyFlightMarkup field. </summary>
		public Nullable<System.Decimal> EconomyFlightMarkup { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeak1RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeak1RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeak2RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeak2RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeak3RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeak3RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeak4RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeak4RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeakKg1RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeakKg1RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeakKg2RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeakKg2RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeakKg3RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeakKg3RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightOffPeakKg4RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightOffPeakKg4RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeak1RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeak1RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeak2RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeak2RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeak3RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeak3RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeak4RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeak4RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeakKg1RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeakKg1RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeakKg2RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeakKg2RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeakKg3RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeakKg3RateId { get; set; }
		/// <summary>Gets or sets the EconomyFlightPeakKg4RateId field. </summary>
		public Nullable<System.Int32> EconomyFlightPeakKg4RateId { get; set; }
		/// <summary>Gets or sets the EconomyMinimumJobRateCodeId field. </summary>
		public Nullable<System.Int32> EconomyMinimumJobRateCodeId { get; set; }
		/// <summary>Gets or sets the EconomyRateCodeId field. </summary>
		public Nullable<System.Int32> EconomyRateCodeId { get; set; }
		/// <summary>Gets or sets the EconomyRun1 field. </summary>
		public Nullable<System.DateTime> EconomyRun1 { get; set; }
		/// <summary>Gets or sets the EconomyRun2 field. </summary>
		public Nullable<System.DateTime> EconomyRun2 { get; set; }
		/// <summary>Gets or sets the EconomyRun3 field. </summary>
		public Nullable<System.DateTime> EconomyRun3 { get; set; }
		/// <summary>Gets or sets the EconomyRun4 field. </summary>
		public Nullable<System.DateTime> EconomyRun4 { get; set; }
		/// <summary>Gets or sets the EconomyRun5 field. </summary>
		public Nullable<System.DateTime> EconomyRun5 { get; set; }
		/// <summary>Gets or sets the EconomyRun6 field. </summary>
		public Nullable<System.DateTime> EconomyRun6 { get; set; }
		/// <summary>Gets or sets the EconomyRun7 field. </summary>
		public Nullable<System.DateTime> EconomyRun7 { get; set; }
		/// <summary>Gets or sets the EconomyRun8 field. </summary>
		public Nullable<System.DateTime> EconomyRun8 { get; set; }
		/// <summary>Gets or sets the EconomyRunItemsExcessRateCodeId field. </summary>
		public Nullable<System.Int32> EconomyRunItemsExcessRateCodeId { get; set; }
		/// <summary>Gets or sets the EconomyRunRateCodeId field. </summary>
		public Nullable<System.Int32> EconomyRunRateCodeId { get; set; }
		/// <summary>Gets or sets the EconomyRuns field. </summary>
		public System.Boolean EconomyRuns { get; set; }
		/// <summary>Gets or sets the EconomyZones field. </summary>
		public System.Boolean EconomyZones { get; set; }
		/// <summary>Gets or sets the ExpressRateCodeId field. </summary>
		public Nullable<System.Int32> ExpressRateCodeId { get; set; }
		/// <summary>Gets or sets the FastPalletExpressRateCodeId field. </summary>
		public Nullable<System.Int32> FastPalletExpressRateCodeId { get; set; }
		/// <summary>Gets or sets the FastPalletStandardRateCodeId field. </summary>
		public Nullable<System.Int32> FastPalletStandardRateCodeId { get; set; }
		/// <summary>Gets or sets the FastPalletSuperRateCodeId field. </summary>
		public Nullable<System.Int32> FastPalletSuperRateCodeId { get; set; }
		/// <summary>Gets or sets the FastParcelRateCodeId field. </summary>
		public Nullable<System.Int32> FastParcelRateCodeId { get; set; }
		/// <summary>Gets or sets the FreightForwardDocuments field. </summary>
		public Nullable<System.Double> FreightForwardDocuments { get; set; }
		/// <summary>Gets or sets the FreightForwardNorthIsland field. </summary>
		public Nullable<System.Double> FreightForwardNorthIsland { get; set; }
		/// <summary>Gets or sets the FreightForwardSouthIsland field. </summary>
		public Nullable<System.Double> FreightForwardSouthIsland { get; set; }
		/// <summary>Gets or sets the GssregularPickupClient field. </summary>
		public Nullable<System.Boolean> GssregularPickupClient { get; set; }
		/// <summary>Gets or sets the GssregularPickupTime field. </summary>
		public Nullable<System.DateTime> GssregularPickupTime { get; set; }
		/// <summary>Gets or sets the HamiltonDayRunDeliveryRateCodeId field. </summary>
		public Nullable<System.Int32> HamiltonDayRunDeliveryRateCodeId { get; set; }
		/// <summary>Gets or sets the HamiltonDayRunPurateCodeId field. </summary>
		public Nullable<System.Int32> HamiltonDayRunPurateCodeId { get; set; }
		/// <summary>Gets or sets the HamiltonNextDayDeliveryRateCodeId field. </summary>
		public Nullable<System.Int32> HamiltonNextDayDeliveryRateCodeId { get; set; }
		/// <summary>Gets or sets the HamiltonNextDayPurateCodeId field. </summary>
		public Nullable<System.Int32> HamiltonNextDayPurateCodeId { get; set; }
		/// <summary>Gets or sets the HamiltonRunAdditionalItemsRateCodeId field. </summary>
		public Nullable<System.Int32> HamiltonRunAdditionalItemsRateCodeId { get; set; }
		/// <summary>Gets or sets the HamiltonRunWeightExcess field. </summary>
		public Nullable<System.Int32> HamiltonRunWeightExcess { get; set; }
		/// <summary>Gets or sets the HamiltonRunWeightLimit field. </summary>
		public Nullable<System.Int32> HamiltonRunWeightLimit { get; set; }
		/// <summary>Gets or sets the HiabHourRateCodeId field. </summary>
		public Nullable<System.Int32> HiabHourRateCodeId { get; set; }
		/// <summary>Gets or sets the IfPickupClientRateUsingZones field. </summary>
		public System.Boolean IfPickupClientRateUsingZones { get; set; }
		/// <summary>Gets or sets the InternetDisplaySavedJobsAsCombo field. </summary>
		public System.Boolean InternetDisplaySavedJobsAsCombo { get; set; }
		/// <summary>Gets or sets the InternetRebate field. </summary>
		public System.Decimal InternetRebate { get; set; }
		/// <summary>Gets or sets the InternetShowPickUpLocation field. </summary>
		public System.Boolean InternetShowPickUpLocation { get; set; }
		/// <summary>Gets or sets the Invoice field. </summary>
		public System.Boolean Invoice { get; set; }
		/// <summary>Gets or sets the InvoiceDue field. </summary>
		public Nullable<System.Int32> InvoiceDue { get; set; }
		/// <summary>Gets or sets the InvoiceEmail field. </summary>
		public System.String InvoiceEmail { get; set; }
		/// <summary>Gets or sets the InvoiceGroupBy field. </summary>
		public System.String InvoiceGroupBy { get; set; }
		/// <summary>Gets or sets the InvoiceMethod field. </summary>
		public System.String InvoiceMethod { get; set; }
		/// <summary>Gets or sets the IsDirectDebit field. </summary>
		public Nullable<System.Boolean> IsDirectDebit { get; set; }
		/// <summary>Gets or sets the IsFeaturedClient field. </summary>
		public System.Boolean IsFeaturedClient { get; set; }
		/// <summary>Gets or sets the JobPrefix field. </summary>
		public System.String JobPrefix { get; set; }
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set; }
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set; }
		/// <summary>Gets or sets the Latitude field. </summary>
		public Nullable<System.Decimal> Latitude { get; set; }
		/// <summary>Gets or sets the Longitude field. </summary>
		public Nullable<System.Decimal> Longitude { get; set; }
		/// <summary>Gets or sets the MarkUp field. </summary>
		public Nullable<System.Decimal> MarkUp { get; set; }
		/// <summary>Gets or sets the MaxJobsPerRun field. </summary>
		public Nullable<System.Int32> MaxJobsPerRun { get; set; }
		/// <summary>Gets or sets the MedicalActive field. </summary>
		public Nullable<System.Boolean> MedicalActive { get; set; }
		/// <summary>Gets or sets the MedicalRunAdditionalItemsRateId field. </summary>
		public Nullable<System.Int32> MedicalRunAdditionalItemsRateId { get; set; }
		/// <summary>Gets or sets the MedicalRunFirstItemRateId field. </summary>
		public Nullable<System.Int32> MedicalRunFirstItemRateId { get; set; }
		/// <summary>Gets or sets the NextFlight1KgrateId field. </summary>
		public Nullable<System.Int32> NextFlight1KgrateId { get; set; }
		/// <summary>Gets or sets the NextFlight1RateId field. </summary>
		public Nullable<System.Int32> NextFlight1RateId { get; set; }
		/// <summary>Gets or sets the NextFlight2KgrateId field. </summary>
		public Nullable<System.Int32> NextFlight2KgrateId { get; set; }
		/// <summary>Gets or sets the NextFlight2RateId field. </summary>
		public Nullable<System.Int32> NextFlight2RateId { get; set; }
		/// <summary>Gets or sets the NextFlight3KgrateId field. </summary>
		public Nullable<System.Int32> NextFlight3KgrateId { get; set; }
		/// <summary>Gets or sets the NextFlight3RateId field. </summary>
		public Nullable<System.Int32> NextFlight3RateId { get; set; }
		/// <summary>Gets or sets the NextFlight4KgrateId field. </summary>
		public Nullable<System.Int32> NextFlight4KgrateId { get; set; }
		/// <summary>Gets or sets the NextFlight4RateId field. </summary>
		public Nullable<System.Int32> NextFlight4RateId { get; set; }
		/// <summary>Gets or sets the NextFlightMarkup field. </summary>
		public Nullable<System.Decimal> NextFlightMarkup { get; set; }
		/// <summary>Gets or sets the NoUtpickUp field. </summary>
		public System.Boolean NoUtpickUp { get; set; }
		/// <summary>Gets or sets the NzPostSiteCode field. </summary>
		public System.String NzPostSiteCode { get; set; }
		/// <summary>Gets or sets the OvernightPickupNotRequired field. </summary>
		public Nullable<System.Boolean> OvernightPickupNotRequired { get; set; }
		/// <summary>Gets or sets the OversizeRateCodeId field. </summary>
		public Nullable<System.Int32> OversizeRateCodeId { get; set; }
		/// <summary>Gets or sets the PpdgraceDays field. </summary>
		public System.Int32 PpdgraceDays { get; set; }
		/// <summary>Gets or sets the Ppdrate field. </summary>
		public Nullable<System.Decimal> Ppdrate { get; set; }
		/// <summary>Gets or sets the PrivateAddressSurchargeRateCodeId field. </summary>
		public Nullable<System.Int32> PrivateAddressSurchargeRateCodeId { get; set; }
		/// <summary>Gets or sets the PromptForEmailAddress field. </summary>
		public System.Boolean PromptForEmailAddress { get; set; }
		/// <summary>Gets or sets the Rate15min field. </summary>
		public Nullable<System.Int32> Rate15min { get; set; }
		/// <summary>Gets or sets the Rate2hr field. </summary>
		public Nullable<System.Int32> Rate2hr { get; set; }
		/// <summary>Gets or sets the Rate30min field. </summary>
		public Nullable<System.Int32> Rate30min { get; set; }
		/// <summary>Gets or sets the Rate45min field. </summary>
		public Nullable<System.Int32> Rate45min { get; set; }
		/// <summary>Gets or sets the Rate75min field. </summary>
		public Nullable<System.Int32> Rate75min { get; set; }
		/// <summary>Gets or sets the Rate90min field. </summary>
		public Nullable<System.Int32> Rate90min { get; set; }
		/// <summary>Gets or sets the RateEconomy field. </summary>
		public Nullable<System.Int32> RateEconomy { get; set; }
		/// <summary>Gets or sets the RateRr field. </summary>
		public Nullable<System.Int32> RateRr { get; set; }
		/// <summary>Gets or sets the RateSat field. </summary>
		public Nullable<System.Int32> RateSat { get; set; }
		/// <summary>Gets or sets the RateShortRr field. </summary>
		public Nullable<System.Int32> RateShortRr { get; set; }
		/// <summary>Gets or sets the RateVan field. </summary>
		public Nullable<System.Int32> RateVan { get; set; }
		/// <summary>Gets or sets the ReferenceAdefineList field. </summary>
		public System.Boolean ReferenceAdefineList { get; set; }
		/// <summary>Gets or sets the ReferenceAmandatory field. </summary>
		public System.Boolean ReferenceAmandatory { get; set; }
		/// <summary>Gets or sets the ReferenceAmessage field. </summary>
		public System.String ReferenceAmessage { get; set; }
		/// <summary>Gets or sets the ReferenceBdefineList field. </summary>
		public System.Boolean ReferenceBdefineList { get; set; }
		/// <summary>Gets or sets the ReferenceBmandatory field. </summary>
		public System.Boolean ReferenceBmandatory { get; set; }
		/// <summary>Gets or sets the ReferenceBmessage field. </summary>
		public System.String ReferenceBmessage { get; set; }
		/// <summary>Gets or sets the ReferenceCdefineList field. </summary>
		public System.Boolean ReferenceCdefineList { get; set; }
		/// <summary>Gets or sets the ReferenceCmandatory field. </summary>
		public System.Boolean ReferenceCmandatory { get; set; }
		/// <summary>Gets or sets the ReferenceCmessage field. </summary>
		public System.String ReferenceCmessage { get; set; }
		/// <summary>Gets or sets the RemoteJobs field. </summary>
		public System.Boolean RemoteJobs { get; set; }
		/// <summary>Gets or sets the RerateJobs field. </summary>
		public System.Boolean RerateJobs { get; set; }
		/// <summary>Gets or sets the RuralDeliveryRateCodeId field. </summary>
		public Nullable<System.Int32> RuralDeliveryRateCodeId { get; set; }
		/// <summary>Gets or sets the Sddenabled field. </summary>
		public Nullable<System.Boolean> Sddenabled { get; set; }
		/// <summary>Gets or sets the Sdrenabled field. </summary>
		public Nullable<System.Boolean> Sdrenabled { get; set; }
		/// <summary>Gets or sets the ShowMap field. </summary>
		public System.Boolean ShowMap { get; set; }
		/// <summary>Gets or sets the SiteId field. </summary>
		public System.Int32 SiteId { get; set; }
		/// <summary>Gets or sets the SiteUrl field. </summary>
		public System.String SiteUrl { get; set; }
		/// <summary>Gets or sets the Smsname field. </summary>
		public System.String Smsname { get; set; }
		/// <summary>Gets or sets the StartingWeightExcess field. </summary>
		public System.Int32 StartingWeightExcess { get; set; }
		/// <summary>Gets or sets the TailLiftRateCodeId field. </summary>
		public Nullable<System.Int32> TailLiftRateCodeId { get; set; }
		/// <summary>Gets or sets the Threshold1 field. </summary>
		public Nullable<System.Int32> Threshold1 { get; set; }
		/// <summary>Gets or sets the Threshold1Amount field. </summary>
		public Nullable<System.Double> Threshold1Amount { get; set; }
		/// <summary>Gets or sets the Threshold2 field. </summary>
		public Nullable<System.Int32> Threshold2 { get; set; }
		/// <summary>Gets or sets the Threshold2Amount field. </summary>
		public Nullable<System.Double> Threshold2Amount { get; set; }
		/// <summary>Gets or sets the Threshold3 field. </summary>
		public Nullable<System.Int32> Threshold3 { get; set; }
		/// <summary>Gets or sets the Threshold3Amount field. </summary>
		public Nullable<System.Double> Threshold3Amount { get; set; }
		/// <summary>Gets or sets the Threshold4 field. </summary>
		public Nullable<System.Int32> Threshold4 { get; set; }
		/// <summary>Gets or sets the Threshold4Amount field. </summary>
		public Nullable<System.Double> Threshold4Amount { get; set; }
		/// <summary>Gets or sets the Threshold5 field. </summary>
		public Nullable<System.Int32> Threshold5 { get; set; }
		/// <summary>Gets or sets the Threshold5Amount field. </summary>
		public Nullable<System.Double> Threshold5Amount { get; set; }
		/// <summary>Gets or sets the TrackingEta field. </summary>
		public Nullable<System.Boolean> TrackingEta { get; set; }
		/// <summary>Gets or sets the TruckBulkRateCodeId field. </summary>
		public Nullable<System.Int32> TruckBulkRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckCitySurchargeRate field. </summary>
		public Nullable<System.Decimal> TruckCitySurchargeRate { get; set; }
		/// <summary>Gets or sets the TruckEconomyExcessZoneRateCodeId field. </summary>
		public Nullable<System.Int32> TruckEconomyExcessZoneRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckEconomyRateCodeId field. </summary>
		public Nullable<System.Int32> TruckEconomyRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessPalletEconomyRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessPalletEconomyRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessPalletFastRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessPalletFastRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessPalletSlowRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessPalletSlowRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessPalletSuperRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessPalletSuperRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessWeightFastRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessWeightFastRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessWeightSlowRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessWeightSlowRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExcessZoneLimit field. </summary>
		public Nullable<System.Int32> TruckExcessZoneLimit { get; set; }
		/// <summary>Gets or sets the TruckExcessZoneRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExcessZoneRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckExpressExcessZoneRateCodeId field. </summary>
		public Nullable<System.Int32> TruckExpressExcessZoneRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckRateCodeId field. </summary>
		public Nullable<System.Int32> TruckRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckRoadRateCodeId field. </summary>
		public Nullable<System.Int32> TruckRoadRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckStandardExcessZoneRateCodeId field. </summary>
		public Nullable<System.Int32> TruckStandardExcessZoneRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckSuperExcessZoneRateCodeId field. </summary>
		public Nullable<System.Int32> TruckSuperExcessZoneRateCodeId { get; set; }
		/// <summary>Gets or sets the TruckWeightLimit field. </summary>
		public Nullable<System.Int32> TruckWeightLimit { get; set; }
		/// <summary>Gets or sets the UcclAccountStatus field. </summary>
		public Nullable<System.Int32> UcclAccountStatus { get; set; }
		/// <summary>Gets or sets the UcclActive field. </summary>
		public System.Boolean UcclActive { get; set; }
		/// <summary>Gets or sets the UcclAddress field. </summary>
		public System.String UcclAddress { get; set; }
		/// <summary>Gets or sets the UcclAverageDaily field. </summary>
		public Nullable<System.Decimal> UcclAverageDaily { get; set; }
		/// <summary>Gets or sets the UcclAverageDailyGroup field. </summary>
		public System.Int32 UcclAverageDailyGroup { get; set; }
		/// <summary>Gets or sets the UcclAwesome field. </summary>
		public System.Boolean UcclAwesome { get; set; }
		/// <summary>Gets or sets the UcclBillingType field. </summary>
		public System.Int32 UcclBillingType { get; set; }
		/// <summary>Gets or sets the UcclCash field. </summary>
		public System.Boolean UcclCash { get; set; }
		/// <summary>Gets or sets the UcclCode field. </summary>
		public System.String UcclCode { get; set; }
		/// <summary>Gets or sets the UcclDateJoined field. </summary>
		public Nullable<System.DateTime> UcclDateJoined { get; set; }
		/// <summary>Gets or sets the UcclDmfirstName field. </summary>
		public System.String UcclDmfirstName { get; set; }
		/// <summary>Gets or sets the UcclDmlastName field. </summary>
		public System.String UcclDmlastName { get; set; }
		/// <summary>Gets or sets the Ucclemail field. </summary>
		public System.String Ucclemail { get; set; }
		/// <summary>Gets or sets the UcclExtraAddress field. </summary>
		public System.String UcclExtraAddress { get; set; }
		/// <summary>Gets or sets the UcclFax field. </summary>
		public System.String UcclFax { get; set; }
		/// <summary>Gets or sets the UcclGroupId field. </summary>
		public Nullable<System.Int32> UcclGroupId { get; set; }
		/// <summary>Gets or sets the UcclGstinc field. </summary>
		public System.Boolean UcclGstinc { get; set; }
		/// <summary>Gets or sets the UcclId field. </summary>
		public System.Int32 UcclId { get; set; }
		/// <summary>Gets or sets the UcclInActiveDate field. </summary>
		public Nullable<System.DateTime> UcclInActiveDate { get; set; }
		/// <summary>Gets or sets the UcclInActiveSetBy field. </summary>
		public System.String UcclInActiveSetBy { get; set; }
		/// <summary>Gets or sets the UcclIndustry field. </summary>
		public Nullable<System.Int32> UcclIndustry { get; set; }
		/// <summary>Gets or sets the UcclInternal field. </summary>
		public System.Boolean UcclInternal { get; set; }
		/// <summary>Gets or sets the UcclInternet field. </summary>
		public System.String UcclInternet { get; set; }
		/// <summary>Gets or sets the UcclLegalName field. </summary>
		public System.String UcclLegalName { get; set; }
		/// <summary>Gets or sets the UcclMcfirstName field. </summary>
		public System.String UcclMcfirstName { get; set; }
		/// <summary>Gets or sets the UcclMclastName field. </summary>
		public System.String UcclMclastName { get; set; }
		/// <summary>Gets or sets the UcclMobile field. </summary>
		public System.String UcclMobile { get; set; }
		/// <summary>Gets or sets the UcclName field. </summary>
		public System.String UcclName { get; set; }
		/// <summary>Gets or sets the UcclNote field. </summary>
		public System.String UcclNote { get; set; }
		/// <summary>Gets or sets the UcclNotes field. </summary>
		public System.String UcclNotes { get; set; }
		/// <summary>Gets or sets the UcclPassword field. </summary>
		public System.String UcclPassword { get; set; }
		/// <summary>Gets or sets the UcclPedal field. </summary>
		public Nullable<System.Int32> UcclPedal { get; set; }
		/// <summary>Gets or sets the UcclPhone field. </summary>
		public System.String UcclPhone { get; set; }
		/// <summary>Gets or sets the UcclPhone2 field. </summary>
		public System.String UcclPhone2 { get; set; }
		/// <summary>Gets or sets the UcclPodrequired field. </summary>
		public Nullable<System.Int32> UcclPodrequired { get; set; }
		/// <summary>Gets or sets the UcclPostal field. </summary>
		public System.String UcclPostal { get; set; }
		/// <summary>Gets or sets the UcclPostCode field. </summary>
		public System.String UcclPostCode { get; set; }
		/// <summary>Gets or sets the UcclRate field. </summary>
		public Nullable<System.Int32> UcclRate { get; set; }
		/// <summary>Gets or sets the UcclRateDoc field. </summary>
		public Nullable<System.Int32> UcclRateDoc { get; set; }
		/// <summary>Gets or sets the UcclRateMainTrunk field. </summary>
		public Nullable<System.Int32> UcclRateMainTrunk { get; set; }
		/// <summary>Gets or sets the UcclRateMainTrunkKg field. </summary>
		public Nullable<System.Int32> UcclRateMainTrunkKg { get; set; }
		/// <summary>Gets or sets the UcclRateNi field. </summary>
		public Nullable<System.Int32> UcclRateNi { get; set; }
		/// <summary>Gets or sets the UcclRateNiweight field. </summary>
		public Nullable<System.Int32> UcclRateNiweight { get; set; }
		/// <summary>Gets or sets the UcclRateOther field. </summary>
		public Nullable<System.Int32> UcclRateOther { get; set; }
		/// <summary>Gets or sets the UcclRateOtherKg field. </summary>
		public Nullable<System.Int32> UcclRateOtherKg { get; set; }
		/// <summary>Gets or sets the UcclRateShorthaul field. </summary>
		public Nullable<System.Int32> UcclRateShorthaul { get; set; }
		/// <summary>Gets or sets the UcclRateShorthaulKg field. </summary>
		public Nullable<System.Int32> UcclRateShorthaulKg { get; set; }
		/// <summary>Gets or sets the UcclRateSi field. </summary>
		public Nullable<System.Int32> UcclRateSi { get; set; }
		/// <summary>Gets or sets the UcclRateSiweight field. </summary>
		public Nullable<System.Int32> UcclRateSiweight { get; set; }
		/// <summary>Gets or sets the UcclReferralNotes field. </summary>
		public System.String UcclReferralNotes { get; set; }
		/// <summary>Gets or sets the UcclReferralSource field. </summary>
		public Nullable<System.Int32> UcclReferralSource { get; set; }
		/// <summary>Gets or sets the UcclSlow field. </summary>
		public Nullable<System.Int32> UcclSlow { get; set; }
		/// <summary>Gets or sets the UcclStaff field. </summary>
		public Nullable<System.Int32> UcclStaff { get; set; }
		/// <summary>Gets or sets the UcclSuburbId field. </summary>
		public Nullable<System.Int32> UcclSuburbId { get; set; }
		/// <summary>Gets or sets the UcclType field. </summary>
		public System.String UcclType { get; set; }
		/// <summary>Gets or sets the UcclUseGroup field. </summary>
		public System.Boolean UcclUseGroup { get; set; }
		/// <summary>Gets or sets the UrgentTonightActive field. </summary>
		public System.Boolean UrgentTonightActive { get; set; }
		/// <summary>Gets or sets the UrgentTonightCategoryId field. </summary>
		public Nullable<System.Int32> UrgentTonightCategoryId { get; set; }
		/// <summary>Gets or sets the UrgentTonightLogo field. </summary>
		public System.String UrgentTonightLogo { get; set; }
		/// <summary>Gets or sets the UrgentTonightSequence field. </summary>
		public Nullable<System.Decimal> UrgentTonightSequence { get; set; }
		/// <summary>Gets or sets the UrgentTonightShow field. </summary>
		public System.Boolean UrgentTonightShow { get; set; }
		/// <summary>Gets or sets the UrgentTonightStyleSheet field. </summary>
		public System.String UrgentTonightStyleSheet { get; set; }
		/// <summary>Gets or sets the UtaddtionalItemRateCodeId field. </summary>
		public Nullable<System.Int32> UtaddtionalItemRateCodeId { get; set; }
		/// <summary>Gets or sets the UtcutOff field. </summary>
		public Nullable<System.DateTime> UtcutOff { get; set; }
		/// <summary>Gets or sets the UtminimumJobsAmount field. </summary>
		public Nullable<System.Decimal> UtminimumJobsAmount { get; set; }
		/// <summary>Gets or sets the UtminimumJobsPerDay field. </summary>
		public Nullable<System.Int32> UtminimumJobsPerDay { get; set; }
		/// <summary>Gets or sets the UtpickupTime field. </summary>
		public Nullable<System.DateTime> UtpickupTime { get; set; }
		/// <summary>Gets or sets the UtrateCodeId field. </summary>
		public Nullable<System.Int32> UtrateCodeId { get; set; }
		/// <summary>Gets or sets the VanStartingWeightExcess field. </summary>
		public Nullable<System.Int32> VanStartingWeightExcess { get; set; }
		/// <summary>Gets or sets the WebServicePassword field. </summary>
		public System.String WebServicePassword { get; set; }
		/// <summary>Gets or sets the WhenBookingJobDisplayFullName field. </summary>
		public System.Boolean WhenBookingJobDisplayFullName { get; set; }
		/// <summary>Gets or sets the XeroId field. </summary>
		public System.String XeroId { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'TucClientContact.TucClient - TucClient.TucClientContacts (m:1)'</summary>
		public virtual List<TucClientContact> TucClientContacts { get; set; }
	}
}
