//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace UrgentHub.Models
{
	/// <summary>Class which represents the entity 'TucClientContact'.</summary>
	public partial class TucClientContact : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucClientContact"/> class.</summary>
		public TucClientContact() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Active field. </summary>
		public System.Boolean Active { get; set; }
		/// <summary>Gets or sets the AllowCookieLogin field. </summary>
		public System.Boolean AllowCookieLogin { get; set; }
		/// <summary>Gets or sets the ContactRoleId field. </summary>
		public Nullable<System.Int32> ContactRoleId { get; set; }
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set; }
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set; }
		/// <summary>Gets or sets the EmailNotificationHasBeenSent field. </summary>
		public System.Boolean EmailNotificationHasBeenSent { get; set; }
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String Fax { get; set; }
		/// <summary>Gets or sets the HasEmail field. </summary>
		public System.Boolean HasEmail { get; set; }
		/// <summary>Gets or sets the LastAccessed field. </summary>
		public Nullable<System.DateTime> LastAccessed { get; set; }
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set; }
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set; }
		/// <summary>Gets or sets the MasterBooker field. </summary>
		public Nullable<System.Int32> MasterBooker { get; set; }
		/// <summary>Gets or sets the MustSelectChildForJob field. </summary>
		public System.Boolean MustSelectChildForJob { get; set; }
		/// <summary>Gets or sets the NumberOfEmailNotificationReminderSent field. </summary>
		public System.Int32 NumberOfEmailNotificationReminderSent { get; set; }
		/// <summary>Gets or sets the ParentContactId field. </summary>
		public Nullable<System.Int32> ParentContactId { get; set; }
		/// <summary>Gets or sets the Password field. </summary>
		public System.String Password { get; set; }
		/// <summary>Gets or sets the Password2 field. </summary>
		public System.String Password2 { get; set; }
		/// <summary>Gets or sets the PromptForEmailAddress field. </summary>
		public System.Boolean PromptForEmailAddress { get; set; }
		/// <summary>Gets or sets the ResetKey field. </summary>
		public System.String ResetKey { get; set; }
		/// <summary>Gets or sets the Salt field. </summary>
		public System.String Salt { get; set; }
		/// <summary>Gets or sets the SendAdhocEmail field. </summary>
		public System.Boolean SendAdhocEmail { get; set; }
		/// <summary>Gets or sets the SharedComputer field. </summary>
		public System.Boolean SharedComputer { get; set; }
		/// <summary>Gets or sets the StaffId field. </summary>
		public Nullable<System.Int32> StaffId { get; set; }
		/// <summary>Gets or sets the UcctClientId field. </summary>
		public Nullable<System.Int32> UcctClientId { get; set; }
		/// <summary>Gets or sets the UcctDirectDial field. </summary>
		public System.String UcctDirectDial { get; set; }
		/// <summary>Gets or sets the UcctEmail field. </summary>
		public System.String UcctEmail { get; set; }
		/// <summary>Gets or sets the UcctFirstname field. </summary>
		public System.String UcctFirstname { get; set; }
		/// <summary>Gets or sets the UcctId field. </summary>
		public System.Int32 UcctId { get; set; }
		/// <summary>Gets or sets the UcctJobTitle field. </summary>
		public System.String UcctJobTitle { get; set; }
		/// <summary>Gets or sets the UcctMobile field. </summary>
		public System.String UcctMobile { get; set; }
		/// <summary>Gets or sets the UcctNotes field. </summary>
		public System.String UcctNotes { get; set; }
		/// <summary>Gets or sets the UcctSurname field. </summary>
		public System.String UcctSurname { get; set; }
		/// <summary>Gets or sets the UserName field. </summary>
		public System.String UserName { get; set; }
		/// <summary>Gets or sets the ValidatedEmail field. </summary>
		public System.Boolean ValidatedEmail { get; set; }
		/// <summary>Gets or sets the WhenEmailNotificationSent field. </summary>
		public Nullable<System.DateTime> WhenEmailNotificationSent { get; set; }
		/// <summary>Gets or sets the WhenEmailValidated field. </summary>
		public Nullable<System.DateTime> WhenEmailValidated { get; set; }
		/// <summary>Gets or sets the WhenEmailValidatedSent field. </summary>
		public Nullable<System.DateTime> WhenEmailValidatedSent { get; set; }
		/// <summary>Gets or sets the WhenLastEmailNotificationReminderSent field. </summary>
		public Nullable<System.DateTime> WhenLastEmailNotificationReminderSent { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'TucClientContact.TucClient - TucClient.TucClientContacts (m:1)'</summary>
		public virtual TucClient TucClient { get; set; }
	}
}
