// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hub.Models;

public partial class TucClient
{
    public int UcclId { get; set; }

    public string UcclName { get; set; }

    public string UcclLegalName { get; set; }

    public string Smsname { get; set; }

    public string UcclCode { get; set; }

    public string UcclAddress { get; set; }

    public string UcclExtraAddress { get; set; }

    public string UcclPostal { get; set; }

    public int? UcclSuburbId { get; set; }

    public string UcclPostCode { get; set; }

    public string UcclPhone { get; set; }

    public string UcclPhone2 { get; set; }

    public string UcclMobile { get; set; }

    public string UcclFax { get; set; }

    public bool Invoice { get; set; }

    public int UcclBillingType { get; set; }

    public string UcclType { get; set; }

    public int? UcclRate { get; set; }

    public int? UcclSlow { get; set; }

    public int? UcclPedal { get; set; }

    public int? UcclRateNi { get; set; }

    public int? UcclRateNiweight { get; set; }

    public int? UcclRateSi { get; set; }

    public int? UcclRateSiweight { get; set; }

    public int? UcclRateDoc { get; set; }

    public int? UcclRateMainTrunk { get; set; }

    public int? UcclRateMainTrunkKg { get; set; }

    public int? UcclRateOther { get; set; }

    public int? UcclRateOtherKg { get; set; }

    public int? UcclRateShorthaul { get; set; }

    public int? UcclRateShorthaulKg { get; set; }

    public int? RateSat { get; set; }

    public int? RateRr { get; set; }

    public int? RateShortRr { get; set; }

    public int? Rate15min { get; set; }

    public int? Rate30min { get; set; }

    public int? Rate45min { get; set; }

    public int? Rate75min { get; set; }

    public int? Rate90min { get; set; }

    public int? Rate2hr { get; set; }

    public int? RateVan { get; set; }

    public int? RuralDeliveryRateCodeId { get; set; }

    public bool UcclGstinc { get; set; }

    public bool UcclCash { get; set; }

    public string UcclNote { get; set; }

    public bool UcclAwesome { get; set; }

    public int? UcclStaff { get; set; }

    public bool UcclInternal { get; set; }

    public DateTime? UcclDateJoined { get; set; }

    public string Ucclemail { get; set; }

    public string UcclInternet { get; set; }

    public int? UcclIndustry { get; set; }

    public string UcclPassword { get; set; }

    public string UcclNotes { get; set; }

    public int? UcclPodrequired { get; set; }

    public int? UcclAccountStatus { get; set; }

    public string UcclDmfirstName { get; set; }

    public string UcclDmlastName { get; set; }

    public string UcclMcfirstName { get; set; }

    public string UcclMclastName { get; set; }

    public bool UcclActive { get; set; }

    public DateTime? UcclInActiveDate { get; set; }

    public string UcclInActiveSetBy { get; set; }

    public int? UcclReferralSource { get; set; }

    public string UcclReferralNotes { get; set; }

    public decimal? UcclAverageDaily { get; set; }

    public int UcclAverageDailyGroup { get; set; }

    public int? UcclGroupId { get; set; }

    public bool UcclUseGroup { get; set; }

    public bool RemoteJobs { get; set; }

    public int SiteId { get; set; }

    public int StartingWeightExcess { get; set; }

    public int AlertLatePickUp { get; set; }

    public int AlertLateDelivery { get; set; }

    public decimal InternetRebate { get; set; }

    public string InvoiceMethod { get; set; }

    public string InvoiceGroupBy { get; set; }

    public bool ReferenceAmandatory { get; set; }

    public string ReferenceAmessage { get; set; }

    public bool ReferenceAdefineList { get; set; }

    public bool ReferenceBmandatory { get; set; }

    public string ReferenceBmessage { get; set; }

    public bool ReferenceBdefineList { get; set; }

    public bool InternetShowPickUpLocation { get; set; }

    public bool IfPickupClientRateUsingZones { get; set; }

    public bool WhenBookingJobDisplayFullName { get; set; }

    public string WebServicePassword { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public bool InternetDisplaySavedJobsAsCombo { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public bool PromptForEmailAddress { get; set; }

    public decimal? MarkUp { get; set; }

    public string UrgentTonightStyleSheet { get; set; }

    public string UrgentTonightLogo { get; set; }

    public bool UrgentTonightShow { get; set; }

    public int? UrgentTonightCategoryId { get; set; }

    public string SiteUrl { get; set; }

    public int? AccountProfileId { get; set; }

    public bool IsFeaturedClient { get; set; }

    public bool UrgentTonightActive { get; set; }

    public decimal? UrgentTonightSequence { get; set; }

    public int? UtrateCodeId { get; set; }

    public int? UtaddtionalItemRateCodeId { get; set; }

    public DateTime? UtpickupTime { get; set; }

    public int? UtminimumJobsPerDay { get; set; }

    public decimal? UtminimumJobsAmount { get; set; }

    public decimal? CourierPercentage { get; set; }

    public string InvoiceEmail { get; set; }

    public bool EconomyActive { get; set; }

    public bool EconomyZones { get; set; }

    public bool EconomyRuns { get; set; }

    public int? EconomyMinimumJobRateCodeId { get; set; }

    public int? EconomyRateCodeId { get; set; }

    public int? EconomyRunRateCodeId { get; set; }

    public DateTime? EconomyRun1 { get; set; }

    public DateTime? EconomyRun2 { get; set; }

    public DateTime? EconomyRun3 { get; set; }

    public DateTime? EconomyRun4 { get; set; }

    public DateTime? EconomyRun5 { get; set; }

    public DateTime? EconomyRun6 { get; set; }

    public DateTime? EconomyRun7 { get; set; }

    public DateTime? EconomyRun8 { get; set; }

    public int? RateEconomy { get; set; }

    public decimal? Ppdrate { get; set; }

    public int PpdgraceDays { get; set; }

    public int? BaggageRateCodeId { get; set; }

    public bool BaggageActive { get; set; }

    public bool? CommissionExclude { get; set; }

    public DateTime? CommissionDate { get; set; }

    public int? FastPalletStandardRateCodeId { get; set; }

    public int? FastPalletExpressRateCodeId { get; set; }

    public int? FastPalletSuperRateCodeId { get; set; }

    public int? ExpressRateCodeId { get; set; }

    public int? TruckRoadRateCodeId { get; set; }

    public int? HiabHourRateCodeId { get; set; }

    public int? FastParcelRateCodeId { get; set; }

    public int? TruckRateCodeId { get; set; }

    public int? TruckBulkRateCodeId { get; set; }

    public int? TruckExcessPalletSlowRateCodeId { get; set; }

    public int? TruckExcessPalletFastRateCodeId { get; set; }

    public int? TailLiftRateCodeId { get; set; }

    public int? TruckExcessWeightSlowRateCodeId { get; set; }

    public int? TruckExcessWeightFastRateCodeId { get; set; }

    public int? OversizeRateCodeId { get; set; }

    public int? PrivateAddressSurchargeRateCodeId { get; set; }

    public int? DangerousServiceRateCodeId { get; set; }

    public int? TruckWeightLimit { get; set; }

    public int? TruckExcessZoneLimit { get; set; }

    public int? TruckExcessZoneRateCodeId { get; set; }

    public double? FreightForwardNorthIsland { get; set; }

    public double? FreightForwardSouthIsland { get; set; }

    public double? FreightForwardDocuments { get; set; }

    public int? VanStartingWeightExcess { get; set; }

    public double? BulkMinimumAmount { get; set; }

    public double? Threshold1Amount { get; set; }

    public double? Threshold2Amount { get; set; }

    public double? Threshold3Amount { get; set; }

    public double? Threshold4Amount { get; set; }

    public double? Threshold5Amount { get; set; }

    public int? Threshold1 { get; set; }

    public int? Threshold2 { get; set; }

    public int? Threshold3 { get; set; }

    public int? Threshold4 { get; set; }

    public int? Threshold5 { get; set; }

    public string DropoffReport { get; set; }

    public int? TruckEconomyRateCodeId { get; set; }

    public int? TruckExcessPalletSuperRateCodeId { get; set; }

    public int? TruckExcessPalletEconomyRateCodeId { get; set; }

    public int? HamiltonDayRunPurateCodeId { get; set; }

    public int? HamiltonDayRunDeliveryRateCodeId { get; set; }

    public int? HamiltonNextDayPurateCodeId { get; set; }

    public int? HamiltonNextDayDeliveryRateCodeId { get; set; }

    public int? HamiltonRunWeightLimit { get; set; }

    public int? HamiltonRunWeightExcess { get; set; }

    public int? EconomyRunItemsExcessRateCodeId { get; set; }

    public int? HamiltonRunAdditionalItemsRateCodeId { get; set; }

    public string AddressExtras { get; set; }

    public string AddressStreetName { get; set; }

    public DateTime? UtcutOff { get; set; }

    public bool RerateJobs { get; set; }

    public bool? OvernightPickupNotRequired { get; set; }

    public bool? MedicalActive { get; set; }

    public int? MedicalRunFirstItemRateId { get; set; }

    public int? MedicalRunAdditionalItemsRateId { get; set; }

    public bool ShowMap { get; set; }

    public bool ReferenceCdefineList { get; set; }

    public bool ReferenceCmandatory { get; set; }

    public string ReferenceCmessage { get; set; }

    public bool DisplayRateRef { get; set; }

    public int? NextFlight1RateId { get; set; }

    public int? NextFlight2RateId { get; set; }

    public int? NextFlight3RateId { get; set; }

    public int? NextFlight4RateId { get; set; }

    public int? NextFlight1KgrateId { get; set; }

    public int? NextFlight2KgrateId { get; set; }

    public int? NextFlight3KgrateId { get; set; }

    public int? NextFlight4KgrateId { get; set; }

    public int? EconomyFlightPeak1RateId { get; set; }

    public int? EconomyFlightPeak2RateId { get; set; }

    public int? EconomyFlightPeak3RateId { get; set; }

    public int? EconomyFlightPeak4RateId { get; set; }

    public int? EconomyFlightPeakKg1rateId { get; set; }

    public int? EconomyFlightPeakKg2rateId { get; set; }

    public int? EconomyFlightPeakKg3rateId { get; set; }

    public int? EconomyFlightPeakKg4rateId { get; set; }

    public int? EconomyFlightOffPeak1RateId { get; set; }

    public int? EconomyFlightOffPeak2RateId { get; set; }

    public int? EconomyFlightOffPeak3RateId { get; set; }

    public int? EconomyFlightOffPeak4RateId { get; set; }

    public int? EconomyFlightOffPeakKg1rateId { get; set; }

    public int? EconomyFlightOffPeakKg2rateId { get; set; }

    public int? EconomyFlightOffPeakKg3rateId { get; set; }

    public int? EconomyFlightOffPeakKg4rateId { get; set; }

    public decimal? NextFlightMarkup { get; set; }

    public decimal? EconomyFlightMarkup { get; set; }

    public decimal? Dgfee { get; set; }

    public decimal? DgdryIce { get; set; }

    public bool? Sddenabled { get; set; }

    public bool? Sdrenabled { get; set; }

    public bool? GssregularPickupClient { get; set; }

    public DateTime? GssregularPickupTime { get; set; }

    public int? InvoiceDue { get; set; }

    public int? TruckEconomyExcessZoneRateCodeId { get; set; }

    public int? TruckStandardExcessZoneRateCodeId { get; set; }

    public int? TruckExpressExcessZoneRateCodeId { get; set; }

    public int? TruckSuperExcessZoneRateCodeId { get; set; }

    public bool? ApplyCitySurcharge { get; set; }

    public decimal? CitySurchargeRate { get; set; }

    public decimal? TruckCitySurchargeRate { get; set; }

    public decimal Discount { get; set; }

    public bool NoUtpickUp { get; set; }

    public int? MaxJobsPerRun { get; set; }

    public string NzPostSiteCode { get; set; }

    public string JobPrefix { get; set; }

    public decimal? AddonPercentage { get; set; }

    public string XeroId { get; set; }

    public bool? IsDirectDebit { get; set; }

    public bool? CreateBulkHomeDeliveryPickup { get; set; }

    public int? BulkHomeDeliveryPickupRateId { get; set; }

    public int? BulkHomeDeliveryVanItemExcess { get; set; }

    public decimal? BulkHomeDeliveryVanItemSurcharge { get; set; }

    public DateTime? BulkAternoonHomePickupTime { get; set; }

    public bool? TrackingEta { get; set; }

    public string SigRequiredDefault { get; set; }

    public bool StripeClient { get; set; }

    public string StripeClientId { get; set; }

    public string PromoCode { get; set; }

    public bool AirNzknownShipper { get; set; }

    public decimal? AirNzmargin { get; set; }

    public bool? ShowNwflight { get; set; }

    public int? JobNumberCounter { get; set; }

    public int? ChilledVanHireRateCodeId { get; set; }

    public double? ChilledVanHireStartingMinutes { get; set; }

    public int? ChilledTruckHireRateCodeId { get; set; }

    public double? ChilledTruckHireStartingMinutes { get; set; }

    public int? FrozenTruckHireRateCodeId { get; set; }

    public double? FrozenTruckHireStartingMinutes { get; set; }

    public bool? DeliverDifferent { get; set; }

    public int? ChilledTruckRateCodeId { get; set; }

    public int? FrozenTruckRateCodeId { get; set; }

    public int? ChilledTruckExcessZoneRateCodeId { get; set; }

    public int? FrozenTruckExcessZoneRateCodeId { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string AddressLine4 { get; set; }

    public string AddressLine5 { get; set; }

    public string AddressLine6 { get; set; }

    public string AddressLine7 { get; set; }

    public string AddressLine8 { get; set; }

    public bool? IsTenantClient { get; set; }

    public int? PreferRatingMethod { get; set; }

    public int? InvoiceTemplateId { get; set; }

    public virtual ICollection<TucClientContact> TucClientContacts { get; set; } = new List<TucClientContact>();
}