//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace UrgentHub.Models
{
	/// <summary>Model builder class for code first development.</summary>
	public partial class UrgentHubModelBuilder
	{
		/// <summary>Builds the model defined in this class with the modelbuilder specified. Called from the generated DbContext</summary>
		/// <param name="modelBuilder">The model builder to build the model with.</param>
		public virtual void BuildModel(ModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema("dbo");
			MapTblUser(modelBuilder.Entity<TblUser>());
			MapTucClient(modelBuilder.Entity<TucClient>());
			MapTucClientContact(modelBuilder.Entity<TucClientContact>());
		}

		/// <summary>Defines the mapping information for the entity 'TblUser'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapTblUser(EntityTypeBuilder<TblUser> config)
		{
			config.ToTable("tblUser");
			config.HasKey(t => t.UserName);
			config.Property(t => t.UserName).HasMaxLength(50);
			config.Property(t => t.FullName).HasMaxLength(50).IsRequired();
			config.Property(t => t.Password).HasMaxLength(50).IsRequired();
			config.Property(t => t.UserGroupId).HasColumnName("UserGroupID");
			config.Property(t => t.LastAccessed);
			config.Property(t => t.Active);
			config.Property(t => t.CourierSecurity);
			config.Property(t => t.CourierId).HasColumnName("CourierID");
			config.Property(t => t.StaffId).HasColumnName("StaffID");
			config.Property(t => t.Created);
			config.Property(t => t.CreatedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.LastModified);
			config.Property(t => t.LastModifiedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.Notes).HasMaxLength(1073741823);
			config.Property(t => t.InternetAccess);
		}

		/// <summary>Defines the mapping information for the entity 'TucClient'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapTucClient(EntityTypeBuilder<TucClient> config)
		{
			config.ToTable("tucClient");
			config.HasKey(t => t.UcclId);
			config.Property(t => t.UcclId).HasColumnName("ucclID").ValueGeneratedOnAdd();
			config.Property(t => t.UcclName).HasColumnName("ucclName").HasMaxLength(75).IsRequired();
			config.Property(t => t.UcclLegalName).HasColumnName("ucclLegalName").HasMaxLength(150).IsRequired();
			config.Property(t => t.Smsname).HasColumnName("SMSName").HasMaxLength(50).IsRequired();
			config.Property(t => t.UcclCode).HasColumnName("ucclCode").HasMaxLength(50).IsRequired();
			config.Property(t => t.UcclAddress).HasColumnName("ucclAddress").HasMaxLength(150);
			config.Property(t => t.UcclExtraAddress).HasColumnName("ucclExtraAddress").HasMaxLength(550);
			config.Property(t => t.UcclPostal).HasColumnName("ucclPostal").HasMaxLength(150);
			config.Property(t => t.UcclSuburbId).HasColumnName("ucclSuburbID");
			config.Property(t => t.UcclPostCode).HasColumnName("ucclPostCode").HasMaxLength(50);
			config.Property(t => t.UcclPhone).HasColumnName("ucclPhone").HasMaxLength(50);
			config.Property(t => t.UcclPhone2).HasColumnName("ucclPhone2").HasMaxLength(50);
			config.Property(t => t.UcclMobile).HasColumnName("ucclMobile").HasMaxLength(50);
			config.Property(t => t.UcclFax).HasColumnName("ucclFax").HasMaxLength(50);
			config.Property(t => t.Invoice);
			config.Property(t => t.UcclBillingType).HasColumnName("ucclBillingType");
			config.Property(t => t.UcclType).HasColumnName("ucclType").HasMaxLength(50);
			config.Property(t => t.UcclRate).HasColumnName("ucclRate");
			config.Property(t => t.UcclSlow).HasColumnName("ucclSlow");
			config.Property(t => t.UcclPedal).HasColumnName("ucclPedal");
			config.Property(t => t.UcclRateNi).HasColumnName("ucclRateNI");
			config.Property(t => t.UcclRateNiweight).HasColumnName("ucclRateNIWeight");
			config.Property(t => t.UcclRateSi).HasColumnName("ucclRateSI");
			config.Property(t => t.UcclRateSiweight).HasColumnName("ucclRateSIWeight");
			config.Property(t => t.UcclRateDoc).HasColumnName("ucclRateDoc");
			config.Property(t => t.UcclRateMainTrunk).HasColumnName("ucclRateMainTrunk");
			config.Property(t => t.UcclRateMainTrunkKg).HasColumnName("ucclRateMainTrunkKG");
			config.Property(t => t.UcclRateOther).HasColumnName("ucclRateOther");
			config.Property(t => t.UcclRateOtherKg).HasColumnName("ucclRateOtherKG");
			config.Property(t => t.UcclRateShorthaul).HasColumnName("ucclRateShorthaul");
			config.Property(t => t.UcclRateShorthaulKg).HasColumnName("ucclRateShorthaulKG");
			config.Property(t => t.RateSat);
			config.Property(t => t.RateRr).HasColumnName("RateRR");
			config.Property(t => t.RateShortRr).HasColumnName("RateShortRR");
			config.Property(t => t.Rate15min);
			config.Property(t => t.Rate30min);
			config.Property(t => t.Rate45min);
			config.Property(t => t.Rate75min);
			config.Property(t => t.Rate90min);
			config.Property(t => t.Rate2hr);
			config.Property(t => t.RateVan);
			config.Property(t => t.RuralDeliveryRateCodeId).HasColumnName("RuralDeliveryRateCodeID");
			config.Property(t => t.UcclGstinc).HasColumnName("ucclGSTInc");
			config.Property(t => t.UcclCash).HasColumnName("ucclCash");
			config.Property(t => t.UcclNote).HasColumnName("ucclNote").HasMaxLength(1073741823);
			config.Property(t => t.UcclAwesome).HasColumnName("ucclAwesome");
			config.Property(t => t.UcclStaff).HasColumnName("ucclStaff");
			config.Property(t => t.UcclInternal).HasColumnName("ucclInternal");
			config.Property(t => t.UcclDateJoined).HasColumnName("ucclDateJoined");
			config.Property(t => t.Ucclemail).HasColumnName("ucclemail").HasMaxLength(100);
			config.Property(t => t.UcclInternet).HasColumnName("ucclInternet").HasMaxLength(100);
			config.Property(t => t.UcclIndustry).HasColumnName("ucclIndustry");
			config.Property(t => t.UcclPassword).HasColumnName("ucclPassword").HasMaxLength(50);
			config.Property(t => t.UcclNotes).HasColumnName("ucclNotes").HasMaxLength(550);
			config.Property(t => t.UcclPodrequired).HasColumnName("ucclPODRequired");
			config.Property(t => t.UcclAccountStatus).HasColumnName("ucclAccountStatus");
			config.Property(t => t.UcclDmfirstName).HasColumnName("ucclDMFirstName").HasMaxLength(50);
			config.Property(t => t.UcclDmlastName).HasColumnName("ucclDMLastName").HasMaxLength(50);
			config.Property(t => t.UcclMcfirstName).HasColumnName("ucclMCFirstName").HasMaxLength(50);
			config.Property(t => t.UcclMclastName).HasColumnName("ucclMCLastName").HasMaxLength(50);
			config.Property(t => t.UcclActive).HasColumnName("ucclActive");
			config.Property(t => t.UcclInActiveDate).HasColumnName("ucclInActiveDate");
			config.Property(t => t.UcclInActiveSetBy).HasColumnName("ucclInActiveSetBy").HasMaxLength(50);
			config.Property(t => t.UcclReferralSource).HasColumnName("ucclReferralSource");
			config.Property(t => t.UcclReferralNotes).HasColumnName("ucclReferralNotes").HasMaxLength(1073741823);
			config.Property(t => t.UcclAverageDaily).HasColumnName("ucclAverageDaily").HasColumnType("money");
			config.Property(t => t.UcclAverageDailyGroup).HasColumnName("ucclAverageDailyGroup");
			config.Property(t => t.UcclGroupId).HasColumnName("ucclGroupID");
			config.Property(t => t.UcclUseGroup).HasColumnName("ucclUseGroup");
			config.Property(t => t.RemoteJobs);
			config.Property(t => t.SiteId).HasColumnName("SiteID");
			config.Property(t => t.StartingWeightExcess);
			config.Property(t => t.AlertLatePickUp);
			config.Property(t => t.AlertLateDelivery);
			config.Property(t => t.InternetRebate).HasColumnType("money");
			config.Property(t => t.InvoiceMethod).HasMaxLength(50);
			config.Property(t => t.InvoiceGroupBy).HasMaxLength(50);
			config.Property(t => t.ReferenceAmandatory).HasColumnName("ReferenceAMandatory");
			config.Property(t => t.ReferenceAmessage).HasColumnName("ReferenceAMessage").HasMaxLength(500);
			config.Property(t => t.ReferenceAdefineList).HasColumnName("ReferenceADefineList");
			config.Property(t => t.ReferenceBmandatory).HasColumnName("ReferenceBMandatory");
			config.Property(t => t.ReferenceBmessage).HasColumnName("ReferenceBMessage").HasMaxLength(500);
			config.Property(t => t.ReferenceBdefineList).HasColumnName("ReferenceBDefineList");
			config.Property(t => t.InternetShowPickUpLocation);
			config.Property(t => t.IfPickupClientRateUsingZones);
			config.Property(t => t.WhenBookingJobDisplayFullName);
			config.Property(t => t.WebServicePassword).HasMaxLength(100);
			config.Property(t => t.Created);
			config.Property(t => t.CreatedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.LastModified);
			config.Property(t => t.LastModifiedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.InternetDisplaySavedJobsAsCombo);
			config.Property(t => t.Longitude).HasColumnType("decimal(18,9)");
			config.Property(t => t.Latitude).HasColumnType("decimal(18,9)");
			config.Property(t => t.PromptForEmailAddress);
			config.Property(t => t.MarkUp).HasColumnType("decimal(18,2)");
			config.Property(t => t.UrgentTonightStyleSheet).HasMaxLength(500);
			config.Property(t => t.UrgentTonightLogo).HasMaxLength(500);
			config.Property(t => t.UrgentTonightShow);
			config.Property(t => t.UrgentTonightCategoryId).HasColumnName("UrgentTonightCategoryID");
			config.Property(t => t.SiteUrl).HasColumnName("SiteURL").HasMaxLength(500);
			config.Property(t => t.AccountProfileId).HasColumnName("AccountProfileID");
			config.Property(t => t.IsFeaturedClient);
			config.Property(t => t.UrgentTonightActive);
			config.Property(t => t.UrgentTonightSequence).HasColumnType("decimal(18,2)");
			config.Property(t => t.UtrateCodeId).HasColumnName("UTRateCodeID");
			config.Property(t => t.UtaddtionalItemRateCodeId).HasColumnName("UTAddtionalItemRateCodeID");
			config.Property(t => t.UtpickupTime).HasColumnName("UTPickupTime");
			config.Property(t => t.UtminimumJobsPerDay).HasColumnName("UTMinimumJobsPerDay");
			config.Property(t => t.UtminimumJobsAmount).HasColumnName("UTMinimumJobsAmount").HasColumnType("money");
			config.Property(t => t.CourierPercentage).HasColumnType("decimal(18,6)");
			config.Property(t => t.InvoiceEmail).HasMaxLength(500);
			config.Property(t => t.EconomyActive);
			config.Property(t => t.EconomyZones);
			config.Property(t => t.EconomyRuns);
			config.Property(t => t.EconomyMinimumJobRateCodeId).HasColumnName("EconomyMinimumJobRateCodeID");
			config.Property(t => t.EconomyRateCodeId).HasColumnName("EconomyRateCodeID");
			config.Property(t => t.EconomyRunRateCodeId).HasColumnName("EconomyRunRateCodeID");
			config.Property(t => t.EconomyRun1);
			config.Property(t => t.EconomyRun2);
			config.Property(t => t.EconomyRun3);
			config.Property(t => t.EconomyRun4);
			config.Property(t => t.EconomyRun5);
			config.Property(t => t.EconomyRun6);
			config.Property(t => t.EconomyRun7);
			config.Property(t => t.EconomyRun8);
			config.Property(t => t.RateEconomy);
			config.Property(t => t.Ppdrate).HasColumnName("PPDRate").HasColumnType("decimal(18,4)");
			config.Property(t => t.PpdgraceDays).HasColumnName("PPDGraceDays");
			config.Property(t => t.BaggageRateCodeId).HasColumnName("BaggageRateCodeID");
			config.Property(t => t.BaggageActive);
			config.Property(t => t.CommissionExclude);
			config.Property(t => t.CommissionDate);
			config.Property(t => t.FastPalletStandardRateCodeId).HasColumnName("FastPalletStandardRateCodeID");
			config.Property(t => t.FastPalletExpressRateCodeId).HasColumnName("FastPalletExpressRateCodeID");
			config.Property(t => t.FastPalletSuperRateCodeId).HasColumnName("FastPalletSuperRateCodeID");
			config.Property(t => t.ExpressRateCodeId).HasColumnName("ExpressRateCodeID");
			config.Property(t => t.TruckRoadRateCodeId).HasColumnName("TruckRoadRateCodeID");
			config.Property(t => t.HiabHourRateCodeId).HasColumnName("HiabHourRateCodeID");
			config.Property(t => t.FastParcelRateCodeId).HasColumnName("FastParcelRateCodeID");
			config.Property(t => t.TruckRateCodeId).HasColumnName("TruckRateCodeID");
			config.Property(t => t.TruckBulkRateCodeId).HasColumnName("TruckBulkRateCodeID");
			config.Property(t => t.TruckExcessPalletSlowRateCodeId).HasColumnName("TruckExcessPalletSlowRateCodeID");
			config.Property(t => t.TruckExcessPalletFastRateCodeId).HasColumnName("TruckExcessPalletFastRateCodeID");
			config.Property(t => t.TailLiftRateCodeId).HasColumnName("TailLiftRateCodeID");
			config.Property(t => t.TruckExcessWeightSlowRateCodeId).HasColumnName("TruckExcessWeightSlowRateCodeID");
			config.Property(t => t.TruckExcessWeightFastRateCodeId).HasColumnName("TruckExcessWeightFastRateCodeID");
			config.Property(t => t.OversizeRateCodeId).HasColumnName("OversizeRateCodeID");
			config.Property(t => t.PrivateAddressSurchargeRateCodeId).HasColumnName("PrivateAddressSurchargeRateCodeID");
			config.Property(t => t.DangerousServiceRateCodeId).HasColumnName("DangerousServiceRateCodeID");
			config.Property(t => t.TruckWeightLimit);
			config.Property(t => t.TruckExcessZoneLimit);
			config.Property(t => t.TruckExcessZoneRateCodeId).HasColumnName("TruckExcessZoneRateCodeID");
			config.Property(t => t.FreightForwardNorthIsland);
			config.Property(t => t.FreightForwardSouthIsland);
			config.Property(t => t.FreightForwardDocuments);
			config.Property(t => t.VanStartingWeightExcess);
			config.Property(t => t.BulkMinimumAmount);
			config.Property(t => t.Threshold1Amount);
			config.Property(t => t.Threshold2Amount);
			config.Property(t => t.Threshold3Amount);
			config.Property(t => t.Threshold4Amount);
			config.Property(t => t.Threshold5Amount);
			config.Property(t => t.Threshold1);
			config.Property(t => t.Threshold2);
			config.Property(t => t.Threshold3);
			config.Property(t => t.Threshold4);
			config.Property(t => t.Threshold5);
			config.Property(t => t.DropoffReport).HasMaxLength(10);
			config.Property(t => t.TruckEconomyRateCodeId).HasColumnName("TruckEconomyRateCodeID");
			config.Property(t => t.TruckExcessPalletSuperRateCodeId).HasColumnName("TruckExcessPalletSuperRateCodeID");
			config.Property(t => t.TruckExcessPalletEconomyRateCodeId).HasColumnName("TruckExcessPalletEconomyRateCodeID");
			config.Property(t => t.HamiltonDayRunPurateCodeId).HasColumnName("HamiltonDayRunPURateCodeID");
			config.Property(t => t.HamiltonDayRunDeliveryRateCodeId).HasColumnName("HamiltonDayRunDeliveryRateCodeID");
			config.Property(t => t.HamiltonNextDayPurateCodeId).HasColumnName("HamiltonNextDayPURateCodeID");
			config.Property(t => t.HamiltonNextDayDeliveryRateCodeId).HasColumnName("HamiltonNextDayDeliveryRateCodeID");
			config.Property(t => t.HamiltonRunWeightLimit);
			config.Property(t => t.HamiltonRunWeightExcess);
			config.Property(t => t.EconomyRunItemsExcessRateCodeId).HasColumnName("EconomyRunItemsExcessRateCodeID");
			config.Property(t => t.HamiltonRunAdditionalItemsRateCodeId).HasColumnName("HamiltonRunAdditionalItemsRateCodeID");
			config.Property(t => t.AddressExtras).HasMaxLength(200);
			config.Property(t => t.AddressStreetName).HasMaxLength(200);
			config.Property(t => t.UtcutOff).HasColumnName("UTCutOff");
			config.Property(t => t.RerateJobs);
			config.Property(t => t.OvernightPickupNotRequired);
			config.Property(t => t.MedicalActive);
			config.Property(t => t.MedicalRunFirstItemRateId).HasColumnName("MedicalRunFirstItemRateID");
			config.Property(t => t.MedicalRunAdditionalItemsRateId).HasColumnName("MedicalRunAdditionalItemsRateID");
			config.Property(t => t.ShowMap);
			config.Property(t => t.ReferenceCdefineList).HasColumnName("ReferenceCDefineList");
			config.Property(t => t.ReferenceCmandatory).HasColumnName("ReferenceCMandatory");
			config.Property(t => t.ReferenceCmessage).HasColumnName("ReferenceCMessage").HasMaxLength(500);
			config.Property(t => t.DisplayRateRef);
			config.Property(t => t.NextFlight1RateId).HasColumnName("NextFlight1RateID");
			config.Property(t => t.NextFlight2RateId).HasColumnName("NextFlight2RateID");
			config.Property(t => t.NextFlight3RateId).HasColumnName("NextFlight3RateID");
			config.Property(t => t.NextFlight4RateId).HasColumnName("NextFlight4RateID");
			config.Property(t => t.NextFlight1KgrateId).HasColumnName("NextFlight1KGRateID");
			config.Property(t => t.NextFlight2KgrateId).HasColumnName("NextFlight2KGRateID");
			config.Property(t => t.NextFlight3KgrateId).HasColumnName("NextFlight3KGRateID");
			config.Property(t => t.NextFlight4KgrateId).HasColumnName("NextFlight4KGRateID");
			config.Property(t => t.EconomyFlightPeak1RateId).HasColumnName("EconomyFlightPeak1RateID");
			config.Property(t => t.EconomyFlightPeak2RateId).HasColumnName("EconomyFlightPeak2RateID");
			config.Property(t => t.EconomyFlightPeak3RateId).HasColumnName("EconomyFlightPeak3RateID");
			config.Property(t => t.EconomyFlightPeak4RateId).HasColumnName("EconomyFlightPeak4RateID");
			config.Property(t => t.EconomyFlightPeakKg1RateId).HasColumnName("EconomyFlightPeakKG1RateID");
			config.Property(t => t.EconomyFlightPeakKg2RateId).HasColumnName("EconomyFlightPeakKG2RateID");
			config.Property(t => t.EconomyFlightPeakKg3RateId).HasColumnName("EconomyFlightPeakKG3RateID");
			config.Property(t => t.EconomyFlightPeakKg4RateId).HasColumnName("EconomyFlightPeakKG4RateID");
			config.Property(t => t.EconomyFlightOffPeak1RateId).HasColumnName("EconomyFlightOffPeak1RateID");
			config.Property(t => t.EconomyFlightOffPeak2RateId).HasColumnName("EconomyFlightOffPeak2RateID");
			config.Property(t => t.EconomyFlightOffPeak3RateId).HasColumnName("EconomyFlightOffPeak3RateID");
			config.Property(t => t.EconomyFlightOffPeak4RateId).HasColumnName("EconomyFlightOffPeak4RateID");
			config.Property(t => t.EconomyFlightOffPeakKg1RateId).HasColumnName("EconomyFlightOffPeakKG1RateID");
			config.Property(t => t.EconomyFlightOffPeakKg2RateId).HasColumnName("EconomyFlightOffPeakKG2RateID");
			config.Property(t => t.EconomyFlightOffPeakKg3RateId).HasColumnName("EconomyFlightOffPeakKG3RateID");
			config.Property(t => t.EconomyFlightOffPeakKg4RateId).HasColumnName("EconomyFlightOffPeakKG4RateID");
			config.Property(t => t.NextFlightMarkup).HasColumnType("decimal(18,2)");
			config.Property(t => t.EconomyFlightMarkup).HasColumnType("decimal(18,2)");
			config.Property(t => t.Dgfee).HasColumnName("DGFee").HasColumnType("decimal(18,2)");
			config.Property(t => t.DgdryIce).HasColumnName("DGDryIce").HasColumnType("decimal(18,2)");
			config.Property(t => t.Sddenabled).HasColumnName("SDDEnabled");
			config.Property(t => t.Sdrenabled).HasColumnName("SDREnabled");
			config.Property(t => t.GssregularPickupClient).HasColumnName("GSSRegularPickupClient");
			config.Property(t => t.GssregularPickupTime).HasColumnName("GSSRegularPickupTime");
			config.Property(t => t.InvoiceDue);
			config.Property(t => t.TruckEconomyExcessZoneRateCodeId).HasColumnName("TruckEconomyExcessZoneRateCodeID");
			config.Property(t => t.TruckStandardExcessZoneRateCodeId).HasColumnName("TruckStandardExcessZoneRateCodeID");
			config.Property(t => t.TruckExpressExcessZoneRateCodeId).HasColumnName("TruckExpressExcessZoneRateCodeID");
			config.Property(t => t.TruckSuperExcessZoneRateCodeId).HasColumnName("TruckSuperExcessZoneRateCodeID");
			config.Property(t => t.ApplyCitySurcharge);
			config.Property(t => t.CitySurchargeRate).HasColumnType("money");
			config.Property(t => t.TruckCitySurchargeRate).HasColumnType("money");
			config.Property(t => t.Discount).HasColumnType("decimal(5,4)");
			config.Property(t => t.NoUtpickUp).HasColumnName("NoUTPickUp");
			config.Property(t => t.MaxJobsPerRun);
			config.Property(t => t.NzPostSiteCode).HasMaxLength(50);
			config.Property(t => t.JobPrefix).HasMaxLength(3);
			config.Property(t => t.AddonPercentage).HasColumnType("numeric(5,4)");
			config.Property(t => t.XeroId).HasMaxLength(50);
			config.Property(t => t.IsDirectDebit);
			config.Property(t => t.CreateBulkHomeDeliveryPickup);
			config.Property(t => t.BulkHomeDeliveryPickupRateId).HasColumnName("BulkHomeDeliveryPickupRateID");
			config.Property(t => t.BulkHomeDeliveryVanItemExcess);
			config.Property(t => t.BulkHomeDeliveryVanItemSurcharge).HasColumnType("money");
			config.Property(t => t.BulkAternoonHomePickupTime);
			config.Property(t => t.TrackingEta).HasColumnName("TrackingETA");
		}

		/// <summary>Defines the mapping information for the entity 'TucClientContact'</summary>
		/// <param name="config">The configuration to modify.</param>
		protected virtual void MapTucClientContact(EntityTypeBuilder<TucClientContact> config)
		{
			config.ToTable("tucClientContact");
			config.HasKey(t => t.UcctId);
			config.Property(t => t.UcctId).HasColumnName("ucctID").ValueGeneratedOnAdd();
			config.Property(t => t.UcctClientId).HasColumnName("ucctClientID");
			config.Property(t => t.UcctFirstname).HasColumnName("ucctFirstname").HasMaxLength(50);
			config.Property(t => t.UcctSurname).HasColumnName("ucctSurname").HasMaxLength(50);
			config.Property(t => t.UcctEmail).HasColumnName("ucctEmail").HasMaxLength(200);
			config.Property(t => t.HasEmail);
			config.Property(t => t.ValidatedEmail);
			config.Property(t => t.UcctJobTitle).HasColumnName("ucctJobTitle").HasMaxLength(50);
			config.Property(t => t.UcctDirectDial).HasColumnName("ucctDirectDial").HasMaxLength(50);
			config.Property(t => t.UcctMobile).HasColumnName("ucctMobile").HasMaxLength(50);
			config.Property(t => t.UcctNotes).HasColumnName("ucctNotes").HasMaxLength(250);
			config.Property(t => t.Fax).HasMaxLength(50);
			config.Property(t => t.UserName).HasMaxLength(200);
			config.Property(t => t.Password).HasMaxLength(50);
			config.Property(t => t.Active);
			config.Property(t => t.AllowCookieLogin);
			config.Property(t => t.LastAccessed);
			config.Property(t => t.ContactRoleId).HasColumnName("ContactRoleID");
			config.Property(t => t.ParentContactId).HasColumnName("ParentContactID");
			config.Property(t => t.SharedComputer);
			config.Property(t => t.MustSelectChildForJob);
			config.Property(t => t.EmailNotificationHasBeenSent);
			config.Property(t => t.WhenEmailNotificationSent);
			config.Property(t => t.NumberOfEmailNotificationReminderSent);
			config.Property(t => t.WhenLastEmailNotificationReminderSent);
			config.Property(t => t.Created);
			config.Property(t => t.CreatedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.LastModified);
			config.Property(t => t.LastModifiedBy).HasMaxLength(50).IsRequired();
			config.Property(t => t.WhenEmailValidated);
			config.Property(t => t.WhenEmailValidatedSent);
			config.Property(t => t.PromptForEmailAddress);
			config.Property(t => t.SendAdhocEmail);
			config.Property(t => t.MasterBooker);
			config.Property(t => t.ResetKey).HasMaxLength(50);
			config.Property(t => t.Password2).HasMaxLength(200);
			config.Property(t => t.Salt).HasMaxLength(64);
			config.Property(t => t.StaffId).HasColumnName("StaffID");
			config.HasOne(t => t.TucClient).WithMany(t => t.TucClientContacts).HasForeignKey(t => t.UcctClientId);
		}
	}


	/// <summary>Extensions class for extension methods used in the model builder code</summary>
	internal static partial class UrgentHubModelBuilderExtensions
	{
		private static readonly string READONLY_ANNOTATION = "custom:readonly";

		/// <summary>Extension method which is used by the context class to determine whether an entity is readonly</summary>
		/// <typeparam name="TEntity">The type of the entity.</typeparam>
		/// <param name="builder">The entity type builder object to augment.</param>
		/// <returns>the passed in entity type builder</returns>
		internal static EntityTypeBuilder<TEntity> IsReadOnly<TEntity>(this EntityTypeBuilder<TEntity> builder)
			where TEntity : class
		{
			builder.HasAnnotation(READONLY_ANNOTATION, true);
			return builder;
		}
		
		/// <summary>Determines whether the passed in entity type has the readonly annotation set.
		/// </summary>
		/// <param name="entity">The entity type to check.</param>
		/// <returns>true if the entity type is marked as read-only, false otherwise</returns>
		public static bool IsReadOnly(this IEntityType entity)
		{
			var annotation = entity.FindAnnotation(READONLY_ANNOTATION);
			return annotation != null && (bool)annotation.Value;
		}
	}
}

